### ISSUE TITLE
反链面板无序列表间距太大了！

### ISSUE THREAD

**Issue by intelion2022** [svchord/Rem-Craft#100]
![image](https://user-images.githubusercontent.com/116488969/210771620-6a44b95c-42fa-438c-a4a0-dd2e16e0929b.png)

**Comment by intelion2022** [comment]
编辑器中无序列表如果也能缩小三分之一左右（即下级列表圆点和上级列表圆点后的文字对齐），为文字腾出更多空间就更好了。

**Comment by svchord** [comment]
最新版已修改并上传，请等待集市打包上架或自行下载仓库到主题文件夹使用
