### ISSUE TITLE
嵌套使用引用块时，聚焦样式错误

### ISSUE THREAD

**Issue by Reverier-Xu** [svchord/Rem-Craft#103]
![image](https://user-images.githubusercontent.com/41937333/212457441-9ba5ad0e-d4d7-4170-881c-664fb01341d2.png)

如图，在列表中使用引用的时候会导致引用左边的那根线变得非常粗，焦点移动到其他块的时候恢复正常。

![image](https://user-images.githubusercontent.com/41937333/212457483-5e6105d3-d9e8-4760-b681-e87756cf53c0.png)

**Comment by svchord** [comment]
请问有更新到最新版吗？我这边没有复现这个问题

**Comment by Reverier-Xu** [comment]
思源 v2.6.3, Rem Craft v2.5.8，应该都是最新的

**Comment by Reverier-Xu** [comment]
抱歉，重启了一下思源之后这个问题就消失了，应该是主题热更新导致有一些样式被缓存下来了，打扰了
