### ISSUE TITLE
暗黑模式主题为浅色

### ISSUE THREAD

**Issue by CoolGIS** [svchord/Rem-Craft#104]
主题版本：2.5.8
思源版本：2.6.3

应用主题后，无论切换暗黑模式还是浅色模式，均为浅色主题。

**Comment by svchord** [comment]
或者你是否使用的是思源2.7.0预览版

**Comment by svchord** [comment]
请问最新版还有没有复现这个问题？

**Comment by iowong** [comment]
2.70 也是这样

**Comment by CoolGIS** [comment]
我的是

> 或者你是否使用的是思源2.7.0预览版

不是预览版，不过我是docker 部署的。

**Comment by CoolGIS** [comment]
> 或者你是否使用的是思源2.7.0预览版

不是预览版，不过我是docker 部署的

**Comment by iowong** [comment]
> 2.70 也是这样

我也是docker版的

**Comment by emengweb** [comment]
同样是docker版，切换到暗黑模式后界面仍然都是浅色主题的样式。

**Comment by emengweb** [comment]
定位到原因了，theme/one-dark/dark.css居然和light.css内容相同，都是浅色主题的配置。
临时解决方案：复制themt/tdesign/dark.css内容，手动设置CSS强行更换主题色。

**Comment by svchord** [comment]
> 定位到原因了，theme/one-dark/dark.css居然和light.css内容相同，都是浅色主题的配置。 临时解决方案：复制themt/tdesign/dark.css内容，手动设置CSS强行更换主题色。

啊这，但我本地没有这个问题，这是怎么回事……

**Comment by emengweb** [comment]
> > 定位到原因了，theme/one-dark/dark.css居然和light.css内容相同，都是浅色主题的配置。 临时解决方案：复制themt/tdesign/dark.css内容，手动设置CSS强行更换主题色。
> 
> 啊这，但我本地没有这个问题，这是怎么回事……

可能是缓存，建议检查下项目源文件dark.css中值是否正确呢 :D

**Comment by svchord** [comment]
等等，你不会是说one-dark下的light吧…那个是暂时废弃的，因为one-dark没有light颜色，所以直接复制的tdesign下的light，dark.css是没问题的。另外，tdesign的dark.css也是暂时废弃了的，因为不好看……

**Comment by emengweb** [comment]
😂 但是代码里调用的暗色模式却使用了one-dark目录中的dark.css文件，所以就导致了黑暗模式依然是明亮的问题，哈哈

Seven Chord ***@***.***> 于 2023年1月30日周一 16:23写道：

**Comment by svchord** [comment]
额不是，你可能没理解我上面那段话，暗色模式只有使用one-dark/dark.css文件才是正确的………另外我已经检查过了，css文件本身内容也没有问题。会不会是docker部署过程导致的问题？我没用过docker版本

**Comment by svchord** [comment]
> 但是one-dark中的dark.css中色值和light.css是一样的——都是用的light.css的色值

我上面想说的就是这个，因为vscode的one-dark并没有明亮模式，所以实际上是light用的dark的色值，而非你所说的相反。你可以和tdesign/light.css对比，或者直接查看`--text-primary`是否是偏白色

**Comment by emengweb** [comment]
原来是这样，那就是dark.css样式没有被正确应用，由于docker部署都是由浏览器直接打开的，可能某些属性支持与打包后的不同，也会导致黑暗模式的css无法覆盖已有样式，只是提供下思路😂

Seven Chord ***@***.***> 于 2023年1月31日周二 10:15写道：

**Comment by svchord** [comment]
我尝试了客户端的“在浏览器打开”功能，暗黑模式还是没有问题…可能是docker特有的问题，之后有空我试试看能不能定位到

**Comment by emengweb** [comment]
十分感谢(❁´ω`❁)

Seven Chord ***@***.***> 于 2023年1月31日周二 11:56写道：

**Comment by svchord** [comment]
请问2.5.12是否还有这个问题？

**Comment by iowong** [comment]
> 
docker版本 依然存在
![微信截图_20230205184355](https://user-images.githubusercontent.com/74191259/216814521-7d9e7464-2ffd-429a-a685-e948673e33fc.png)

**Comment by h2o2o** [comment]
我通过浏览器开发者模式查看其它可以正常切换显示模式的主题请求，将文件修改如下可以实现正常的切换显示模式

>  思源笔记 Docker 镜像 2.7.5 Arm64  测试正常

1. 在 `themes/Rem Craft/theme.css` 开头添加下面代码
```css
@import"/appearance/themes/Rem Craft/theme/tdesign/dark.css";
```
2. 将 `themes/Rem Craft/theme/tdesign/light.css` 开始位置的 `:root` 替换为如下代码
```css
:root[data-theme-mode=light]
```
3. 将 `themes/Rem Craft/theme/tdesign/dark.css` 开始位置的 `:root` 替换为如下代码
```css
:root[data-theme-mode=dark]
```

目前仅测试切换显示模式正常，不知道是否会导致其他的Bug，仅此抛砖引玉希望能给大佬一点点思路。@svchord

**Comment by svchord** [comment]
![image](https://user-images.githubusercontent.com/61345763/221603482-df1cfa56-8017-463f-8a1c-ce7a4c6aad01.png)

我尝试了一下docker安装，发现主题目录缺少文件，不清楚是什么原因

**Comment by svchord** [comment]
最新版已修改并上传，请等待集市打包上架或自行下载仓库到主题文件夹使用
