### ISSUE TITLE
思源logo显示问题

### ISSUE THREAD

**Issue by lentikr** [svchord/Rem-Craft#106]
不知道是如此设计还是bug？

鼠标未悬浮状态如下：
![image](https://user-images.githubusercontent.com/95539012/213121348-af141065-9c31-409a-95d4-004218312d94.png)

鼠标悬浮时状态如下：
![image](https://user-images.githubusercontent.com/95539012/213121441-29b3413b-3e2a-44cd-b868-026f7fde7e18.png)

**Comment by svchord** [comment]
是bug，但我这边没能复现，请问主题版本是否为2.5.9，思源版本是否为2.7.0，以及操作系统是哪个？

**Comment by lentikr** [comment]
> 是bug，但我这边没能复现，请问主题版本是否为2.5.9，思源版本是否为2.7.0，以及操作系统是哪个？

主题版本2.5.9
![image](https://user-images.githubusercontent.com/95539012/213129721-2301a048-2b18-438f-a28e-6f679ddc9b96.png)

思源版本2.7.0
![image](https://user-images.githubusercontent.com/95539012/213129792-055cb39c-9f75-4769-b6f2-11eb73f897e3.png)

操作系统Win10
![image](https://user-images.githubusercontent.com/95539012/213129840-b677e3a4-5d3b-427b-b232-fa606d31a265.png)

**Comment by lentikr** [comment]
也尝试了刷新缓存（开发者工具勾选取消缓存，ctrl+f5），没有效果

**Comment by svchord** [comment]
是否是其他的代码片段导致的？

**Comment by lentikr** [comment]
> 是否是其他的代码片段导致的？

我只有一个设置字体的代码片段，尝试了，关闭了也无效，如果不好定位问题的话就这样吧，不太影响使用。
![1674053482262](https://user-images.githubusercontent.com/95539012/213203148-0589f038-7142-4190-9f7b-e078c72aa38e.png)

**Comment by lentikr** [comment]
我的另一台windows设备出现了一样的问题。

**Comment by svchord** [comment]
主题更新下个版本的时候再看看吧，我这边确实没定位到

**Comment by xy0124** [comment]
其实D把这个LOGO放出来就很奇怪，界面UI奇怪，作者大大可以直接给去掉

**Comment by svchord** [comment]
但其实我这个主题早在去年就加了这个logo了……官方下个版本要删了，我估计还是会加回来，那时候应该就不会出现问题了

**Comment by xy0124** [comment]
更新了，果然去掉，整体和谐统一太多了。
![1`V 5A21(NE%`P`%$P7BX9H](https://user-images.githubusercontent.com/99000021/215273748-e6e36177-65d9-46b1-a40a-2071dd69887b.jpg)

**Comment by svchord** [comment]
> 更新了，果然去掉，整体和谐统一太多了。 ![1V 5A21(NE%P`%$P7BX9H](https://user-images.githubusercontent.com/99000021/215273748-e6e36177-65d9-46b1-a40a-2071dd69887b.jpg)

抱歉，我个人还是更喜欢有logo，所以就在下个版本的主题加回来了，到时候你可以用css片段去掉

**Comment by svchord** [comment]
> 更新了，果然去掉，整体和谐统一太多了。 ![1V 5A21(NE%P`%$P7BX9H](https://user-images.githubusercontent.com/99000021/215273748-e6e36177-65d9-46b1-a40a-2071dd69887b.jpg)

我猜你觉得不和谐的原因是没开dock栏……
![image](https://user-images.githubusercontent.com/61345763/215274851-e9e205ff-8b4d-4f4e-9348-90cdbf48cd04.png)

**Comment by xy0124** [comment]
啊？又加回来了啊！
怎么去掉呢？

**Comment by svchord** [comment]
> 啊？又加回来了啊！ 怎么去掉呢？

用下面的css片段暂时顶顶：

```css
#toolbar::before{
display:none;
}
```

**Comment by SsparKluo** [comment]
> > 更新了，果然去掉，整体和谐统一太多了。 ![1V 5A21(NE%P`%$P7BX9H](https://user-images.githubusercontent.com/99000021/215273748-e6e36177-65d9-46b1-a40a-2071dd69887b.jpg)
> 
> 我猜你觉得不和谐的原因是没开dock栏…… ![image](https://user-images.githubusercontent.com/61345763/215274851-e9e205ff-8b4d-4f4e-9348-90cdbf48cd04.png)

那也许可以试试只在打开侧边栏的时候加logo？

**Comment by svchord** [comment]
> > > 更新了，果然去掉，整体和谐统一太多了。 ![1V 5A21(NE%P`%$P7BX9H](https://user-images.githubusercontent.com/99000021/215273748-e6e36177-65d9-46b1-a40a-2071dd69887b.jpg)
> > 
> > 
> > 我猜你觉得不和谐的原因是没开dock栏…… ![image](https://user-images.githubusercontent.com/61345763/215274851-e9e205ff-8b4d-4f4e-9348-90cdbf48cd04.png)
> 
> 那也许可以试试只在打开侧边栏的时候加logo？

已经有想法了，不过最近时间不多，下个版本再优化吧，觉得丑的话先用css片段顶顶

**Comment by svchord** [comment]
最新版已实现logo跟随边栏自动变化，请等待集市打包上架或自行下载仓库到主题文件夹使用
