### ISSUE TITLE
”思源笔记/SiYuan“显示异常

### ISSUE THREAD

**Issue by hetingrui** [svchord/Rem-Craft#108]
确认思源笔记是否为最新版本：2.7.2

确认本地 Rem Craft 是否为最新版本：2.5.10

确认关闭其他代码片段后是否能重现问题：是

问题描述：浅色模式时，思源笔记为浅色
<img width="209" alt="image" src="https://user-images.githubusercontent.com/32641980/216517143-5bcb83a1-8853-4fdf-8522-cbd88fea7da1.png">

操作系统：windows 11 22h2

**Comment by svchord** [comment]
集市已更新
