### ISSUE TITLE
在左右分屏阅读pdf时，顶部标题异外出现

### ISSUE THREAD

**Issue by hetingrui** [svchord/Rem-Craft#109]
确认思源笔记是否为最新版本：是

确认本地 Rem Craft 是否为最新版本：是

确认关闭其他代码片段后是否能重现问题：是

问题描述：在左右分屏阅读pdf时，顶部标题异外出现
<img width="194" alt="image" src="https://user-images.githubusercontent.com/32641980/216760987-7923db95-4ac6-4947-99f0-1325f9d6364f.png">
移动后消失
<img width="92" alt="image" src="https://user-images.githubusercontent.com/32641980/216760999-52904e67-0dbf-4d06-b372-eb154b7692c0.png">

操作系统：Win11 22H2

**Comment by svchord** [comment]
收到，下个版本修复

**Comment by svchord** [comment]
最新版已修改并上传，请等待集市打包上架或自行下载仓库到主题文件夹使用
