### ISSUE TITLE
日历面板的更新

### ISSUE THREAD

**Issue by HowcanoeWang** [svchord/Rem-Craft#110]
右上角的悬浮日历，可以使用下面这个更新，支持自定义日记模板路径以及修复一些bug
https://github.com/HowcanoeWang/calendar

**Comment by svchord** [comment]
刚看到，但是大佬你的项目维护起来太麻烦了，所以我就自己写了另一个[项目](https://github.com/svchord?tab=repositories)，逻辑流程基本是搬运大佬你的

**Comment by HowcanoeWang** [comment]
落伍了，只会写JavaScript，我也是在大佬的基础上瞎改的
