### ISSUE TITLE
思源笔记以PDF格式导出后标记文本格式错误

### ISSUE THREAD

**Issue by shanjun2026** [svchord/Rem-Craft#111]
确认思源笔记是否为最新版本：2.7.3

确认本地 Rem Craft 是否为最新版本：2.5.12

确认关闭其他代码片段后是否能重现问题：是

问题描述：思源笔记以PDF格式导出后，使用过‘标记’的文本会出现格式错误，同时标记的显示方式也对文本的阅读不是很友好，是否可以将其改成全覆盖文本的形式？
![image](https://user-images.githubusercontent.com/47911446/217517987-dac0dc0e-cf62-48f2-8f08-aa6e19fa70d2.png)

操作系统：windows 10

**Comment by svchord** [comment]
导出问题我没能复现，不过这么看效果确实不算好，下个版本我改一下你看看效果，顺便看看导出还会不会有问题

**Comment by shanjun2026** [comment]
嗯嗯，非常感谢！

**Comment by svchord** [comment]
请问最新版效果怎么样？

**Comment by shanjun2026** [comment]
嗯嗯，最新版效果没问题了👍，感谢！
![image](https://user-images.githubusercontent.com/47911446/219021300-e20b801b-860c-47ec-9109-aa4434e438b0.png)
