### ISSUE TITLE
左下角面板打开后无法关闭

### ISSUE THREAD

**Issue by heimi98** [svchord/Rem-Craft#112]
确认思源笔记是否为最新版本：是

确认本地 Rem Craft 是否为最新版本：是

确认关闭其他代码片段后是否能重现问题：是

问题描述：左下角面板（例如标签面板）打开后无法关闭。

操作系统：win11

**Comment by svchord** [comment]
抱歉，我这边没能复现，能提供一下具体的复现步骤和录屏吗

**Comment by heimi98** [comment]
> 抱歉，我这边没能复现，能提供一下具体的复现步骤和录屏吗

![动画](https://user-images.githubusercontent.com/56879067/219525259-98894c24-21bf-40e2-984c-be138f64cc4a.gif)

**Comment by svchord** [comment]
我这边还是没有复现这个问题，请问你是docker环境吗？我在群里也有一个说是出现了这个问题，是docker环境、思源v2.7.3，我目前不知道是哪个原因导致的

**Comment by heimi98** [comment]
不是 docker，莫名其妙又好了。

**Comment by svchord** [comment]
那估计是缓存之类的问题，这个issue我就先关了
