### ISSUE TITLE
关系图无法全屏

### ISSUE THREAD

**Issue by heimi98** [svchord/Rem-Craft#113]
思源笔记版本号：2.7.5
本地 Rem Craft 版本号：2.6.0

确认关闭其他代码片段后是否能重现问题：是

问题描述：关系图无法全屏

复现步骤：
![image](https://user-images.githubusercontent.com/56879067/219825756-6dbdf33b-70e3-4f05-aca6-59d2bf39ec9a.png)

操作系统：win11

**Comment by svchord** [comment]
收到，我看看怎么改

**Comment by svchord** [comment]
最新版已修改并上传，请等待集市打包上架或自行下载仓库到主题文件夹使用
