### ISSUE TITLE
希望对超宽表格添加横向的滚动条

### ISSUE THREAD

**Issue by frostime** [svchord/Rem-Craft#114]
思源笔记版本号：2.7.5

本地 Rem Craft 版本号：2.6.0

确认关闭其他代码片段后是否能重现问题：是

问题描述：

默认主题下，比较宽的表格有一个横向的滚动条，从而防止单元格全部都挤在一起。
![image](https://user-images.githubusercontent.com/27268127/220244092-9c4df3ce-0d19-49af-89e7-38a53e687c21.png)
而使用Rem-Craft的时候，宽表格全部都会挤在一起，看上去很难看
![image](https://user-images.githubusercontent.com/27268127/220244699-fe11441f-ebcd-451d-bd23-0d7e7e7353d3.png)

复现步骤：

保证表格宽度大于屏幕正常显示范围即可。

建议处理方式：

- 最优解：可以仿照 Savor 主题的方案，添加表格显示方案切换

    
![image](https://user-images.githubusercontent.com/27268127/220245691-20398356-c797-4121-866a-45ccb92ac85a.png)

- 次优解：直接上表格按照滚动条形式显示

操作系统：

Windows 10

**Comment by svchord** [comment]
短时间做不到savor那种，我直接不换行吧

**Comment by frostime** [comment]
> 短时间做不到savor那种，我直接不换行吧

可以的，只要保证加个滚动条让表格能正常显示、不挤在一起就行，其他的都是功能糖而已。

**Comment by svchord** [comment]
最新版已修改并上传，请等待集市打包上架或自行下载仓库到主题文件夹使用
