### ISSUE TITLE
关于/网络代理显示不全

### ISSUE THREAD

**Issue by itachaaa** [svchord/Rem-Craft#118]
思源笔记版本号：
2.7.10
本地 Rem Craft 版本号：
v2.6.1
确认关闭其他代码片段后是否能重现问题：
Y
问题描述：
v2.6.1
复现步骤：
![image](https://user-images.githubusercontent.com/31896600/226329980-4e7c1ce4-45a9-4040-835e-cdeddf95561e.png)
切换此主题，点击设置、关于、网络代理
操作系统：
WIN11

**Comment by svchord** [comment]
没太理解显示不全是指什么，我试着输入一些字符串，没什么问题啊

**Comment by svchord** [comment]
我搞明白了，看看怎么改，下个主题版本应该能修复

**Comment by svchord** [comment]
最新版已修改并上传

**Comment by itachaaa** [comment]
嗯嗯 我应该提供期望或者正常的效果会更容易理解，楼主的issue模板里也可以加一下
