### ISSUE TITLE
缩进的无序列表在被折叠后无法再展开

### ISSUE THREAD

**Issue by peixxxxxx** [svchord/Rem-Craft#119]
思源笔记版本号：v2.7.10

本地 Rem Craft 版本号：v2.6.1

确认关闭其他代码片段后是否能重现问题：没有添加其他代码片段

问题描述：缩进的无序列表在被折叠后无法再展开

复现步骤：1.创建多行无序列表块 2.缩进第一行以下的其他无序列表块 3.点击块旁边的小三角尝试展开

操作系统：windows10

**Comment by svchord** [comment]
![无序列表测试](https://user-images.githubusercontent.com/61345763/226384319-6b534f3e-bca0-4c1c-b384-4de72885a539.gif)

我这边没能复现

**Comment by peixxxxxx** [comment]
发现使用【无序列表】的快捷键：
折叠 【ctrl + ↑】 和 展开【ctrl + ↓】有效，可以绕过这个 bug
