### ISSUE TITLE
反链面板在右下方时，下方的浮动状态栏会遮挡「提及」面板的按钮

### ISSUE THREAD

**Issue by LJpLJ** [svchord/Rem-Craft#121]
思源笔记版本号：2.8.3

本地 Rem Craft 版本号：2.6.2

确认关闭其他代码片段后是否能重现问题：

问题描述：反链面板在右下方时，下方的浮动状态栏会遮挡「提及」面板的按钮

复现步骤：rt

操作系统：win11
![截图_20230405233002](https://user-images.githubusercontent.com/1617882/230129760-bac2de2b-c03f-42ce-9aa4-9ef525f349c1.png)

**Comment by svchord** [comment]
最新版已修改并上传，请等待集市打包上架或自行下载仓库到主题文件夹使用
