### ISSUE TITLE
左下角的通知横条挡住了标签按钮和部分标签

### ISSUE THREAD

**Issue by MaiXiaochai** [svchord/Rem-Craft#122]
思源笔记版本号：v2.8.6

本地 Rem Craft 版本号：v2.6.6

确认关闭其他代码片段后是否能重现问题：出现

问题描述：https://ld246.com/article/1683276994742
![image](https://user-images.githubusercontent.com/28613162/236593326-6b68ac4b-5a26-487d-a803-9172d48b6851.png)

复现步骤：

操作系统：win10专业版 1909

**Comment by svchord** [comment]
抱歉，我这边没能复现，请问你是通过 `config.js` 关闭的底部状态栏特殊样式的吗？

![image](https://github.com/svchord/Rem-Craft/assets/61345763/50c4d86a-fddc-47a4-970a-294fdb4123c8)

**Comment by svchord** [comment]
代码片段指的是`设置菜单 - 外观 - 代码片段`，部分代码片段可能会和主题有冲突，但如果你之前不了解这个功能的话，就应该不是这个的问题。这个主题也没有日志，如果不急的话，我建议等我更新下个版本之后，卸载重装主题试试

**Comment by MaiXiaochai** [comment]
哦哦，好的，辛苦大佬！感谢大佬做了这么好的主题。
