### ISSUE TITLE
集市改版后所有按钮不显示，UI不适配

### ISSUE THREAD

**Issue by gdy106** [svchord/Rem-Craft#124]
思源笔记版本号：2.8.7

本地 Rem Craft 版本号：2.6.6

确认关闭其他代码片段后是否能重现问题：能

问题描述：集市改版后所有按钮消失，UI不适配
![image](https://github.com/svchord/Rem-Craft/assets/57566668/8e79ba94-84f6-4281-b434-c4fc21314072)
![image](https://github.com/svchord/Rem-Craft/assets/57566668/9b915822-a352-4c3d-bb8c-260a7dd93d56)

复现步骤：

操作系统：

**Comment by svchord** [comment]
新版已发布，等集市更新上架
