### ISSUE TITLE
两个文字显示的小问题

### ISSUE THREAD

**Issue by komoechan** [svchord/Rem-Craft#126]
思源笔记版本号：2.9.0

本地 Rem Craft 版本号：2.6.7

确认关闭其他代码片段后是否能重现问题：

问题描述：
![WX20230609-120942@2x](https://github.com/svchord/Rem-Craft/assets/66232948/938203fb-f7e3-4dc7-9831-93c570652ebc)
![WX20230609-121009@2x](https://github.com/svchord/Rem-Craft/assets/66232948/a45c9b0b-362c-4d2d-8838-50230572429e)

复现步骤：打开特定页面即可

操作系统：MacOS Ventura 13.4 (22F66)

**Comment by svchord** [comment]
这是主题版本的问题，最新版本是2.6.10，你可以卸载重装主题试试
