### ISSUE TITLE
页签右键点击移动到新窗口，打开后的页签会和关闭开启栏重合

### ISSUE THREAD

**Issue by DreamsCat** [svchord/Rem-Craft#127]
思源笔记版本号：2.9.1

本地 Rem Craft 版本号：2.6.10

确认关闭其他代码片段后是否能重现问题：是

问题描述：
页签右键点击移动到新窗口，打开后的页签会和关闭开启栏重合
<img width="403" alt="image" src="https://github.com/svchord/Rem-Craft/assets/52805134/b8374557-1870-4108-9427-db48d4396fc3">
使用思源原皮肤，不会出现此问题

复现步骤：
<img width="285" alt="image" src="https://github.com/svchord/Rem-Craft/assets/52805134/556cff5e-0274-49e3-8267-b1bed9a84d90">

操作系统：
Macos13.4

**Comment by DreamsCat** [comment]
@svchord

**Comment by svchord** [comment]
收到，下个版本看看

**Comment by svchord** [comment]
已更新修复
