### ISSUE TITLE
行距过大

### ISSUE THREAD

**Issue by DreamsCat** [svchord/Rem-Craft#128]
思源笔记版本号：2.9.1

本地 Rem Craft 版本号：2.6.10

确认关闭其他代码片段后是否能重现问题：是

问题描述：
看这行距，有点太大了
<img width="945" alt="image" src="https://github.com/svchord/Rem-Craft/assets/52805134/cf36a7b0-0db2-4fa0-8d63-68aa483c59af">

这是官方的，行距比较小
<img width="943" alt="image" src="https://github.com/svchord/Rem-Craft/assets/52805134/aa0c1b68-30c3-4c2a-ac93-ff3697000700">

能调整一下吗？看着非常怪

操作系统：MacOS 13.4

**Comment by DreamsCat** [comment]
@svchord

**Comment by svchord** [comment]
已更新
