### ISSUE TITLE
思源笔记-设置-集市中已下载插件页面UI显示错位

### ISSUE THREAD

**Issue by otto88956** [svchord/Rem-Craft#131]
思源笔记版本号：
2.9.3
本地 Rem Craft 版本号：
v2.6.11
确认关闭其他代码片段后是否能重现问题：
是
问题描述：
思源笔记-设置-集市中已下载插件页面UI显示错位
复现步骤：
1、思源笔记2.9.3版本-集市-已下载页面新增一键启用/关闭插件功能
2、该按钮造成了思源笔记-设置-集市中已下载插件页面UI显示错位
操作系统：
Mac os [13.4]
![iShot_2023-06-28_10 04 53](https://github.com/svchord/Rem-Craft/assets/137133811/b8da0e10-9cc0-4356-9b0e-3138c7d50f7a)

**Comment by svchord** [comment]
已更新修复
