### ISSUE TITLE
添加题头图后，按钮显示与标题重叠

### ISSUE THREAD

**Issue by CKlimeths** [svchord/Rem-Craft#132]
思源笔记版本号：v2.9.4

本地 Rem Craft 版本号：v2.6.11

确认关闭其他代码片段后是否能重现问题：是

问题描述：添加题头图后，按钮显示与标题重叠

复现步骤：
任意页面添加题头图，emoji下的按钮显示与标题重叠。
![image](https://github.com/svchord/Rem-Craft/assets/86591721/46b5b6ed-cd9f-4e22-b135-e36ebc60951f)
没有添加题头图的页面则显示正常。
![image](https://github.com/svchord/Rem-Craft/assets/86591721/df89f736-b080-4dd4-bf6b-f489ecfb8ec4)

操作系统：
版本	Windows 10 LTSC 2021  内部版本	19044.3086

**Comment by svchord** [comment]
已更新修复
