### ISSUE TITLE
建议增加类似张亮主题 / 呼出菜单排列方式

### ISSUE THREAD

**Issue by xy0124** [svchord/Rem-Craft#15]
![image](https://user-images.githubusercontent.com/99000021/160140919-0e68616d-b648-45ef-ab45-e7e1c14085c0.png)

**Comment by xy0124** [comment]
另外，个人有打开左右两列对比两个版本看书的习惯，编辑器输入宽度写死了，这一点是在哪里可以修改？我个人改一下，方便书籍的显示，跟方便阅读。谢谢了

**Comment by EberhardLin** [comment]
> 另外，个人有打开左右两列对比两个版本看书的习惯，编辑器输入宽度写死了，这一点是在哪里可以修改？我个人改一下，方便书籍的显示，跟方便阅读。谢谢了

见本项目code页下方介绍：
![image](https://user-images.githubusercontent.com/98400319/160223463-4c4d950f-0718-48af-a137-a5873fd1ded9.png)
![image](https://user-images.githubusercontent.com/98400319/160223468-c99dd043-cca9-4646-8261-8c5b234c0b75.png)
 第3点就是。

**Comment by xy0124** [comment]
谢谢指路

**Comment by xy0124** [comment]
不是程序员行业者完全懵逼了，就用不去改了。谢啦

**Comment by zqhjl** [comment]
> 另外，个人有打开左右两列对比两个版本看书的习惯，编辑器输入宽度写死了，这一点是在哪里可以修改？我个人改一下，方便书籍的显示，跟方便阅读。谢谢了

编辑器输入宽度好像不影响分屏显示吧

**Comment by xy0124** [comment]
不影响分屏显示。
因为宽度显示，两边的白边比较大，分屏之后可查看文档就更少而已。只是查看文档本身的视觉上的，没功能上的问题的。

**Comment by svchord** [comment]
最新版已增加该功能并上传，请等待集市打包上架或自行下载最新发布版本使用
