### ISSUE TITLE
代码块问题

### ISSUE THREAD

**Issue by cqc01** [svchord/Rem-Craft#152]
思源笔记版本号：3.1.10

本地 Rem Craft 版本号：2.6.12

确认关闭其他代码片段后是否能重现问题：是

问题描述：1、代码块上下方空了一大片，使用默认主题正常；2、行号显示后默认向右移动一段距离，使用默认主题正常

复现步骤：

操作系统：win10
![image](https://github.com/user-attachments/assets/169e748b-4bf7-4c79-bcdb-c621fcb90d37)
![image](https://github.com/user-attachments/assets/9c9b63f8-19c1-4b91-a51e-858118705e2c)

**Comment by terwer** [comment]
我修复了一下代码块，看看咋样

![image](https://github.com/user-attachments/assets/cb1aa337-cd52-47c7-ad81-e82b15eee40e)

![image](https://github.com/user-attachments/assets/3a7f06e0-7b15-43ad-9e1d-fc0290bbd7d7)

![image](https://github.com/user-attachments/assets/c0c78c8f-9239-485a-ad89-1323be7a8d6f)

![image](https://github.com/user-attachments/assets/7295be58-9e85-49a5-b2ff-b24d67137a0a)

下载替换即可，满意的话可以 pr 一下：

[theme.css.zip](https://github.com/user-attachments/files/18002252/theme.css.zip)
