### ISSUE TITLE
思源"定义块引用计数浮窗高亮引用处锚文本“功能的跟进

### ISSUE THREAD

**Issue by JOYCELEEEEE** [svchord/Rem-Craft#18]
这个功能思源目前已经实现了，但是 rem craft 主题下好像不能实现该功能

大佬考虑跟进一下吗

具体见 https://github.com/siyuan-note/siyuan/issues/4446

感谢！

**Comment by zqhjl** [comment]
已解决，下个版本发布后会关闭该issue

**Comment by JOYCELEEEEE** [comment]
感谢大佬！

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

________________________________
发件人: Reckless ***@***.***>
发送时间: Friday, May 20, 2022 10:52:31 AM
收件人: zqhjl/Rem-Craft ***@***.***>
抄送: JOYCELEEEEE ***@***.***>; Author ***@***.***>
主题: Re: [zqhjl/Rem-Craft] 思源"定义块引用计数浮窗高亮引用处锚文本“功能的跟进 (Issue #18)


已解决，下个版本发布后会关闭该issue

―

**Comment by svchord** [comment]
最新版已修复并上传，请等待集市打包上架或自行下载最新发布版本使用
