### ISSUE TITLE
希望顶栏可以在鼠标没有悬停的时候隐藏掉

### ISSUE THREAD

**Issue by woaihuangxueying** [svchord/Rem-Craft#19]
1. 顶栏按钮的利用率不高：
顶栏的这几个按钮，日记、边栏、同步在第一设置以后基本上就不会怎么动；
搜索平常也是用 ctl+f/p代替；
也就是 白天/夜间主题的切换可能用的多一点。

2. 顶栏的灰色和下面的白色相比，有些突兀，并且汉字相对符号也更加奇怪。

综上，希望可以向 Chrome-A4主题那样，平常鼠标没有悬停的时候隐藏掉。 悬停以后再显示。

![image](https://user-images.githubusercontent.com/104878505/167874474-685dc461-3c8a-44b7-a3b1-00b753662573.png)
[](url)

**Comment by zqhjl** [comment]
顶栏的布局我也想了好久，但是一直想不出来解决方案，我整体的布局是参考win11的任务管理器，所以直接隐藏顶栏总觉得怪怪的

**Comment by EberhardLin** [comment]
我就是觉得汉字顶栏而且是固定住的才喜欢Rem Craft的，第一个是汉字图标辨识度高，而且够大我鼠标移过去不用过多分散注意力，第二个是固定顶栏不用鼠标移过去后等他浮现再去找需要的图标。
总结一句话，辨识度高，用着很舒服。
当然这和我个人喜好、习惯有关，所以我这么说不是觉得该issue有啥不好，只是表达下还有喜欢现有版本顶栏设计的用户：）

**Comment by allynlin** [comment]
顶栏的布局原本我用的是 notion 的全套主题，后来就是因为改变了顶栏布局后就弃用了，顶栏布局这个如果有设置项会更好一些，如果能自定义的话，我个人并不喜欢隐藏顶栏布局，隐藏了顶栏总觉得太怪了。
其实如果有一个开关，可以自定义是否能隐藏顶栏，应该是这个 Issue 最好的解决方案。

**Comment by svchord** [comment]
我留着这个issue是因为我之前想做一个收缩展开顶栏按钮的功能，把左上角的图标当做开关按钮，但是后来精力有限，就一直没时间做了。

**Comment by svchord** [comment]
如果稳定的话，顶栏布局应该不会有大的变化了，所以这个issue我就关了吧
