### ISSUE TITLE
考虑出dark主题么

### ISSUE THREAD

**Issue by haoshaoyang** [svchord/Rem-Craft#2]
如题

**Comment by zqhjl** [comment]
一直有考虑的，而且把颜色和样式解耦也是最近一直在做的，就是工作量比较大…

再加上自己对排版设计一直不太满意，所以可能要等稳定后再发布。

> 最近想抄的semi design有dark的颜色参考，等解耦完成，再抄一抄就行了

**Comment by shanyan-wcx** [comment]
能否考虑把dark主题的配色使用one-dark的配色，或者把one-dark主题的菜单采用rem-craft的样式？思源默认的菜单栏用起来实在不舒服，还是vscode的样式顺手，我又特别喜欢one-dark的配色。现在one-dark主题外面一圈都是黑色，实在是不太好看。或者单独出一个rem-craft for one-dark主题也行。另外设置的上面两个圆角显示异常，这是bug还是只能这样？

**Comment by svchord** [comment]
最新版已修改并上传，请等待集市打包上架或自行下载最新发布版本使用。

> 另外我没有使用one dark的配色，之后我可能会专门出一个主题
