### ISSUE TITLE
感觉正文有点空荡荡的

### ISSUE THREAD

**Issue by yuyuyu-github** [svchord/Rem-Craft#20]
相同的一个目录笔记的首页，
这是 点赞最多的那个白天主题
![QQ截图20220511223915](https://user-images.githubusercontent.com/37429029/167877245-ce702fa1-5484-4713-bc2c-95316f384aad.png)

这个是Remcraft
![QQ截图20220511223943](https://user-images.githubusercontent.com/37429029/167877284-d9571b31-6893-4ab1-88d3-468bb1b8dc91.png)

**Comment by zqhjl** [comment]
这个页边距我是抄的notion，以后可能会学萌新大佬搞个config.json，不过最近在重构，应该没什么精力搞，我把issue先留在这吧？

**Comment by zqhjl** [comment]
这个页边距我是抄的notion，以后可能会学萌新大佬搞个config.json，不过最近在重构，应该没什么精力搞，我把issue先留在这吧？

**Comment by svchord** [comment]
最新版已经出了自适应宽度，不过我还是更建议关闭那个设置，因为我的主题和最新功能不太适配…
