### ISSUE TITLE
反馈一下

### ISSUE THREAD

**Issue by GUTA-x** [svchord/Rem-Craft#23]
我打算自定义主题，出现点击后整个页面颜色混乱的情况，我不知道问题出在哪里，希望可以帮我看一下，非常感谢。

还有一个问题，好像高亮的时候不能跨行选择，就是如果高亮一句话，这句话分布在多行，那么高亮这句话的时候，要么就不行，要么就高亮一点。

![image](https://user-images.githubusercontent.com/108705482/177232242-90254847-e7e8-4fd6-a299-1f46b677ade1.png)

**Comment by svchord** [comment]
目前好像不能兼容思源自带的自定义主题功能，之后应该会尝试模仿dark主题做一个config.json

**Comment by GUTA-x** [comment]
好的，感谢回信。期待你的更新！ 

从 Windows 版邮件发送

发件人: Seven Chord
发送时间: 2022年7月5日 11:22
收件人: svchord/Rem-Craft
抄送: GUTA-x; Author
主题: Re: [svchord/Rem-Craft] 反馈一下 (Issue #23)

目前好像不能兼容思源自带的自定义主题功能，之后应该会尝试模仿dark主题做一个config.json

**Comment by svchord** [comment]
官方已经有了代码片段功能，你有什么自定义需求可以新开一个issue，这个issue我先关了
