### ISSUE TITLE
新版本文档树也太丑了

### ISSUE THREAD

**Issue by hbdzh** [svchord/Rem-Craft#25]

**Comment by svchord** [comment]
额，是指什么地方，文档前的圆点？还是笔记本的样式？

**Comment by hbdzh** [comment]
> 额，是指什么地方，文档前的圆点？还是笔记本的样式？

笔记本的样式，以前的很简洁，比现在的好看。
另外作者有没有试过把软件的背景色改成白色？其实整个背景变成白色也挺好看的。

**Comment by svchord** [comment]
我主要是想区分笔记本和普通文档，原来的问文字加粗太粗糙，现在这个可能太吸引注意力，但想不出来更好的形式了…

**Comment by svchord** [comment]
最新版已修改并上传，请等待集市打包上架或自行下载最新发布版本使用
