### ISSUE TITLE
反馈引用块内部分CSS错误

### ISSUE THREAD

**Issue by syan2018** [svchord/Rem-Craft#26]
![QQ截图20220715000644](https://user-images.githubusercontent.com/24589615/179027560-987733b1-0b28-4c2d-9925-8a81ce6b0785.png)

其一是引用块嵌套段落块时，段落块选中高亮范围有点错误

还有就是希望引用块内使用其它容器字体可以同样置灰（如图中列表

**Comment by svchord** [comment]
收到，下午看看怎么改

**Comment by svchord** [comment]
我已经修好了，但是还在犹豫要不要发版，因为这个小版本没有解决多少问题，所以想问下你觉得这个问题紧急吗，不紧急的话我把明暗切换的功能做好之后再发版

**Comment by syan2018** [comment]
大赞，等一手夜晚模式

**Comment by syan2018** [comment]
还发现了引用块中嵌入表格错误的问题，不知道修复了没有嘿嘿嘿

**Comment by svchord** [comment]
最新版已修改并上传，请等待集市打包上架或自行下载最新发布版本使用
