### ISSUE TITLE
行内公式的字体有些奇怪

### ISSUE THREAD

**Issue by Li-C-l** [svchord/Rem-Craft#27]
用dark主题的时候行内公式是一种奇怪的字体，正体无法正常显示，且数字是那种高矮不同的。请问有什么办法能够解决么？
![Screenshot 2022-07-26 232251](https://user-images.githubusercontent.com/110047498/181045918-dc3ea3f0-10d9-4894-902f-5d66fecf6614.png)

**Comment by svchord** [comment]
感谢反馈，下个版本修复
