### ISSUE TITLE
功能菜单悬浮显示不完整

### ISSUE THREAD

**Issue by JARVISia** [svchord/Rem-Craft#29]
![Snipaste_2022-08-02_12-22-17](https://user-images.githubusercontent.com/16850140/182291228-2a53cbda-e855-4272-943f-0104160709de.png)

**Comment by svchord** [comment]
感谢反馈，我看看怎么改

**Comment by svchord** [comment]
最新版已修改并上传，请等待集市打包上架或自行下载最新发布版本使用
