### ISSUE TITLE
打开图片时操作小按钮显示的bug

### ISSUE THREAD

**Issue by JARVISia** [svchord/Rem-Craft#30]
明亮模式下这里的图标有显示的bug，应该是与本身的白色融合了
![image](https://user-images.githubusercontent.com/16850140/183899237-f2411bf4-57ac-4711-9102-7e2678058674.png)

暗黑模式没有
![image](https://user-images.githubusercontent.com/16850140/183899406-1991aba2-9467-4a61-a9d1-3f4bb32963f9.png)

**Comment by svchord** [comment]
最新版已修改并上传，请等待集市打包上架或自行下载最新发布版本使用
