### ISSUE TITLE
【反馈】超级块“外观”四个样式显示BUG

### ISSUE THREAD

**Issue by EberhardLin** [svchord/Rem-Craft#32]
![image](https://user-images.githubusercontent.com/98400319/187080996-49730e8a-d647-4ca8-bfab-16c91607c044.png)
算是bug吧，如图，四个样式在实际显示中有问题，提个issue。
![image](https://user-images.githubusercontent.com/98400319/187081022-4fc9e2c7-810f-4d93-b8df-00aac1852099.png)

**Comment by EberhardLin** [comment]
补充描述：正常来讲应该是默认主题下这样的
![image](https://user-images.githubusercontent.com/98400319/187081073-5958da2e-3020-41cd-8541-52bd9abbbef6.png)
Rem Craft主题中，标题左侧边距过小，上面边距过大，不太美观。

**Comment by svchord** [comment]
![image](https://user-images.githubusercontent.com/61345763/188139913-b408502b-32f2-4fb9-ba94-e69712aa23c9.png)

最新版已修改，还未上传集市

**Comment by EberhardLin** [comment]
ok！非常nice

**Comment by svchord** [comment]
最新版已修改并上传，请等待集市打包上架或自行下载最新发布版本使用
