### ISSUE TITLE
父任务块已完成，会导致未完成的子任务块变成完成样式

### ISSUE THREAD

**Issue by EberhardLin** [svchord/Rem-Craft#34]
![image](https://user-images.githubusercontent.com/98400319/188669112-f79b7b3f-8ce5-4872-b525-c5d46d4ed582.png)
![image](https://user-images.githubusercontent.com/98400319/188669158-1cca42a1-4eb5-4c65-af02-801b05649932.png)

**Comment by svchord** [comment]
这个我一直以为挺符合日常使用逻辑的…你是有什么特殊需求吗

**Comment by EberhardLin** [comment]
应该不算吧特殊需求，参考截图，我读完了第一章开始整理自己对第一章的笔记，所以我缩进成子级任务块，但我还没整理完成所以没有打勾。
这个时候我认为子任务块应该是未完成样式。

**Comment by EberhardLin** [comment]
不过我在想这是主题的问题吗。因为我测试了默认主题和第三方主题，发现默认主题因为打勾了也不会发生什么变化，但第三方主题都会将未完成的子任务块变成已完成的样式。
![image](https://user-images.githubusercontent.com/98400319/188670348-221187fb-8b9f-48a2-b2c5-6985197e89a5.png)
![image](https://user-images.githubusercontent.com/98400319/188670381-2933d2ed-94e8-4c2a-be03-22645d56a4dc.png)
![image](https://user-images.githubusercontent.com/98400319/188670448-5671181d-cd43-4920-a54e-5c3cc2fd6137.png)
所以我在想这会不会是思源的问题。

**Comment by EberhardLin** [comment]
算了我换个使用思路吧，感觉这不算是主题和思源的问题，算是我自己使用的问题。
![image](https://user-images.githubusercontent.com/98400319/188671434-380983d3-857c-4648-811d-a5aa14d0c2f8.png)

**Comment by EberhardLin** [comment]
> 是这样，主题一般都想把已完成的任务区别出来，这一点默认主题没做到；但是任务块会有很多种子块，大家不想一种一种写特殊情况，就会写成所有子块都更改样式。
> 
> 我感觉你这种场景，可以把父列表换成有序列表，例如：
> 
> ![image](https://user-images.githubusercontent.com/61345763/188673089-d98d5cc9-cfbd-46e5-9d8b-a69564c20fbd.png)

嗯，我寻思着也是这么个道理，我换下使用思路就行了，阿里嘎多
