### ISSUE TITLE
什么时候出自定义css

### ISSUE THREAD

**Issue by iowong** [svchord/Rem-Craft#35]
**上一个版本我还能f12一点点的选择修改 这个版本有点看不懂**
提几点 emoji太小了 完全看不清
![微信截图_20220907143138](https://user-images.githubusercontent.com/74191259/188805486-9363c5bd-a8f0-4255-b1b2-f81a3a1bada3.png)
/bq 表情面板有点问题
![微信截图_20220907143150](https://user-images.githubusercontent.com/74191259/188805624-a58094a5-5775-474e-8b3b-3a294c0fb9b5.png)
这文字太小了 看着字有些发虚
![微信截图_20220907143309](https://user-images.githubusercontent.com/74191259/188805810-a03433e1-57a6-48cc-b5e9-fd153548fd06.png)
这个图标好像错乱了
![微信截图_20220907143650](https://user-images.githubusercontent.com/74191259/188806472-b827fdc6-f947-44fb-91a1-12695241f8db.png)

最后给几个之前修改的截图参考下
![微信截图_20220907143845](https://user-images.githubusercontent.com/74191259/188807069-a73be01f-01cf-4906-bee2-4c13ea6234fb.png)

**Comment by svchord** [comment]
1. emoji我个人不太喜欢你最后截图里面那么大的，下个版本我稍微调大一点试试
2. /bq 表情面板我改好了，下个版本更新
3. 超链接icon问题同上
4. 我之后会出一个自定义主题色的功能，当然你现在也可以直接去`themes/one-dark/dark.css`里修改颜色

**Comment by svchord** [comment]
自定义功能估计要等一段时间，我先把一些小问题更新了吧

**Comment by svchord** [comment]
官方已经有了代码片段功能，你有什么自定义需求可以新开一个issue，这个issue我先关了
