### ISSUE TITLE
导出文件样式丢失

### ISSUE THREAD

**Issue by allynlin** [svchord/Rem-Craft#37]
导出的HTML、PDF等文件没法保留设置的各种颜色、居中等设置

**Comment by svchord** [comment]
确定是我的主题导致的吗？

**Comment by allynlin** [comment]
我切换到默认主题导出是没有任何问题的，我没法确定一定是你的主题导致的这个问题，确实也没有测试其他主题，是不是都一样

**Comment by allynlin** [comment]
目前来说，我只测试了 notion-light 主题和 默认主题，这两个主题都是没有任何问题的，所以暂时怀疑应该是主题导致的问题。其余的主题也并没有一个个尝试，还是希望您能查看一下，是不是主题的问题导致的它无法导出样式

**Comment by svchord** [comment]
请问可以贴一下您的测试文档吗？我刚刚试了下，我这边默认主题导出预览时也没有自定义的字体颜色、背景颜色和居中等

**Comment by allynlin** [comment]
[组件基础（上）.sy.zip](https://github.com/svchord/Rem-Craft/files/9533828/sy.zip)

**Comment by allynlin** [comment]
这是刚提到的导出丢失样式的文档，您可以测试一下，关于默认主题导出和您的主题导出以及编辑器内预览的样式

**Comment by allynlin** [comment]
导出预览和实际导出的效果还存在差异，具体还是要看实际导出 PDF 或 HTML 的样式

**Comment by svchord** [comment]
我这边定位到了问题来源，字体颜色问题是因为我之前把自己添加的css变量从`theme.css`中抽了出来；居中是没问题的。

但是如果想要完全修改好，会影响我主题之后的功能添加计划，所以你看下这样能不能接受：每次更新主题后，把`themes/tdesign/light.css`里面的内容，全部复制粘贴到根目录下的`theme.css`的开头，这样导出就没有问题了

**Comment by svchord** [comment]
啊，我突然找到了两全其美的办法，不需要你们操作了，等下个版本更新吧

**Comment by svchord** [comment]
最新版已修改并上传，请等待集市打包上架或自行下载最新发布版本使用
