### ISSUE TITLE
有一个小边框存在

### ISSUE THREAD

**Issue by htoooth** [svchord/Rem-Craft#38]
发现上，左，右 有一个 2个 px 的距离，导致颜色不一样

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/1717023/189317568-773e59a0-9793-4b6f-b88d-b7956d13f135.png">

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/1717023/189317657-1e2d2aae-1f92-41cf-9de1-921ca769b257.png">

**Comment by svchord** [comment]
我这边没找到，看图上也看不太出来……能定位到元素吗？

**Comment by svchord** [comment]
啊，黑色那张图看出来了，不过奇怪的是我这边是正常的。你要不要看看有没有更新主题？

**Comment by htoooth** [comment]
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/1717023/189510403-ab657768-6419-45f4-a25b-e63528c23c77.png">

在这里

**Comment by htoooth** [comment]
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/1717023/189510633-b969de82-359f-4083-b75d-d7464b1cd02e.png">

**Comment by htoooth** [comment]
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/1717023/189510689-b6a0f005-8ee7-4fc1-bb4c-c82f50f57540.png">

**Comment by svchord** [comment]
请问你有确认过主题版本吗？我这边确实是正常的啊

**Comment by svchord** [comment]
![image](https://user-images.githubusercontent.com/61345763/189510949-b0c0939d-eb26-4a31-88c5-c6079b81e3c3.png)

**Comment by svchord** [comment]
算了，我下个版本给body加个底色看看能不能解决这个问题

**Comment by svchord** [comment]
我看了一下，已经加过了，应该是主题缓存的问题

**Comment by svchord** [comment]
试试这样：开发者工具-网络-停用缓存
然后打开console 录入 window.location.reload()

**Comment by svchord** [comment]
我找到问题原因了，是有个`.body-win32`的选择器出了问题，下个版本就能解决

**Comment by htoooth** [comment]
> 我找到问题原因了，是有个`.body-win32`的选择器出了问题，下个版本就能解决

谢谢，我自己用的代码编译的，直接加了一个底色，感觉还是颜色不正。还有编辑器的宽度要能控制一下吧，可编辑区域有点小了，不过我也自己调整了一下代码。

**Comment by svchord** [comment]
我有计划之后适配官方的自适应宽度功能，不过如果想要自定义宽度的话，可能还是需要修改变量自行编译了

**Comment by svchord** [comment]
最新版已修改并上传，请等待集市打包上架或自行下载最新发布版本使用
