### ISSUE TITLE
滚动条会浮在链接面板上

### ISSUE THREAD

**Issue by FantasyDream** [svchord/Rem-Craft#39]
如图所示
![image](https://user-images.githubusercontent.com/24907641/189383574-635a0660-3fc3-4c99-8172-47a6d13d183a.png)

**Comment by svchord** [comment]
收到，下个版本修复

**Comment by svchord** [comment]
请下个版本更新的时候再看看，我这边没有复现

**Comment by FantasyDream** [comment]
思源笔记用户指南的这篇文章应该能复现, 我这重新安装了主题也这样
![image](https://user-images.githubusercontent.com/24907641/189511508-8c460729-0357-477a-a254-a342ebd22f3a.png)

**Comment by svchord** [comment]
我这边还是没有，应该是主题缓存的问题

**Comment by svchord** [comment]
试试这样：开发者工具-网络-停用缓存
然后打开console  录入 window.location.reload()

**Comment by FantasyDream** [comment]
不行, 我清了好几次缓存了, 还是有这个问题, 是不是我的思源版本的问题, 我的是最新版2.1.14

Seven Chord ***@***.***> 于2022年9月11日周日 11:53写道：

**Comment by svchord** [comment]
我也是用的这个版本的思源啊…奇怪了

**Comment by FantasyDream** [comment]
嗯, 好的

**Comment by svchord** [comment]
最新版已修改并上传，你看看还有没有问题

**Comment by FantasyDream** [comment]
还是不行, 我重新安装了一下思源和主题, 仍然没有变化
![image](https://user-images.githubusercontent.com/24907641/189528860-41bba681-d7fb-4803-bc1f-3881cbc94581.png)
![image](https://user-images.githubusercontent.com/24907641/189528862-f0518b51-1084-411e-84d5-62d5508d365d.png)

应该是滚动条的z-index变成了1000000导致的
我试着把b3-menu的z-index调成了1000001就正常了, 调成1000000仍然不正常
```css
.b3-menu {
    z-index: 1000001;
}
```
![image](https://user-images.githubusercontent.com/24907641/189529049-48e57bff-a245-42d4-b6a8-91965788dd10.png)

**Comment by svchord** [comment]
可是我明明写了滚动条的 `z-index: 1`……而且我在其他文档都没发现有这个问题，比如你看看内容块类型

**Comment by FantasyDream** [comment]
应该是已经修复了, 我又试了试其他页面, 现在只有思源笔记用户指南的什么是内容块这篇还有这个问题, 其他都没问题了, 麻烦大佬了
