### ISSUE TITLE
PDF导出窗口需要适配一下

### ISSUE THREAD

**Issue by EberhardLin** [svchord/Rem-Craft#40]
![image](https://user-images.githubusercontent.com/98400319/189512603-b0e7d96f-6376-4bf7-8ef8-608487482ca4.png)
最近的更新，PDF导出的窗口应该是有改动，可以跟着改动一下。
默认主题：
![image](https://user-images.githubusercontent.com/98400319/189512619-6e7a29f9-1844-4b72-a99c-c2e3977fe006.png)

**Comment by EberhardLin** [comment]
首先是右侧灰色区域的按钮们需要显示出来。其次可以给整个窗口外观加上一条蓝色描线？第二点是个人想法

**Comment by svchord** [comment]
收到，下个版本更新

**Comment by svchord** [comment]
最新版已修改并上传，请等待集市打包上架或自行下载最新发布版本使用
