### ISSUE TITLE
v2.1.3 导出 HTML 文件代码块显示异常

### ISSUE THREAD

**Issue by allynlin** [svchord/Rem-Craft#41]
![Snipaste_2022-09-11_21-36-37](https://user-images.githubusercontent.com/99640011/189530540-20cfbb40-6cc3-411b-82f6-427bcb89c76c.png)

有一层灰蒙蒙的感觉

**Comment by svchord** [comment]
![image](https://user-images.githubusercontent.com/61345763/189530761-07848a67-05bc-48f8-88ff-cc9927a522a6.png)

我这边是正常的啊

**Comment by allynlin** [comment]
很奇怪，我重启一下电脑吧，再排查一下

**Comment by allynlin** [comment]
[函数进阶.sy.zip](https://github.com/svchord/Rem-Craft/files/9542699/sy.zip)

**Comment by allynlin** [comment]
如果可以的话，能排查一下吗，我这里导出了几个都是这样灰蒙蒙的
深色模式下导出的，不知道是不是只有深色模式存在问题

**Comment by allynlin** [comment]
确实深色模式下导出存在异常

**Comment by svchord** [comment]
![image](https://user-images.githubusercontent.com/61345763/189532404-4860a5e6-03a6-44b6-8db5-b7ca7208af6d.png)

我用了你的文件，而且也是暗黑模式，还是正常的啊

**Comment by allynlin** [comment]
就是这个图片，感觉颜色和浅色模式下导出的有点区别，就是代码块背景和代码块高亮感觉有点不对劲，和浅色模式下导出的文件做个对比就知道了

**Comment by svchord** [comment]
![image](https://user-images.githubusercontent.com/61345763/189533922-99eb584b-ec20-456f-88c9-bf1f39786eb8.png)

这是我的明亮模式，代码块背景没区别，代码块高亮确实和暗黑模式下的样式有区别。

但是这不是我的主题的问题，而是暗黑模式下导出后的代码块高亮风格，仍然是你在设置菜单里选择的暗黑风格，背景却默认是明亮风格（比如我的代码风格就是`atom-on-dark.min.css`），所以我的建议是导出时还是使用明亮模式

**Comment by allynlin** [comment]
好，我去看一下代码块高亮风格的问题，这个确实我也没看过

**Comment by allynlin** [comment]
![Snipaste_2022-09-12_12-16-46](https://user-images.githubusercontent.com/99640011/189572954-fc4b2214-1f4b-4ba1-a82a-4cfcf280dfa3.png)
![Snipaste_2022-09-12_12-16-53](https://user-images.githubusercontent.com/99640011/189572963-45d2e67f-510b-4586-b60d-a3092aa5acb3.png)
图一是深色模式下导出的，图二是明亮模式下导出的，是代码高亮颜色有区别，这个应该就是在代码块高亮颜色选项中导致的，还是明亮模式导出会更好些，找到原因了。
