### ISSUE TITLE
中英文空格

### ISSUE THREAD

**Issue by allynlin** [svchord/Rem-Craft#42]
能不能以主题的形式做一个这样的功能，在中英文之间自动生成一个英文空格，这个还是挺实用的。目前 siyuan 给出的解决方案是在文档左上角使用优化排版的方式实现，这个需要对每一篇文档手动优化排版。如果可以由主题直接实现会更方便

**Comment by svchord** [comment]
中英文间隔应该不是主题能做到的了，不过可以做到在行内代码块、公式块之类的行内特殊块的两边增加间隔，但因为已经有优化排版功能，所以我没做
