### ISSUE TITLE
命名/别名与文本似乎重叠了

### ISSUE THREAD

**Issue by SsparKluo** [svchord/Rem-Craft#45]
<img width="581" alt="微信截图_20221004144617" src="https://user-images.githubusercontent.com/32617864/193752380-fd0a5b93-cbb5-4cc9-862b-a7670fc42ec4.png">

主题应该只修改了字体。

**Comment by svchord** [comment]
收到，下个版本修复

**Comment by svchord** [comment]
最新版已修改并上传，请等待集市打包上架或自行下载最新发布版本使用
