### ISSUE TITLE
窗口无法拖拽移动的问题

### ISSUE THREAD

**Issue by xgblack** [svchord/Rem-Craft#49]
更新新版之后，出现了鼠标按住顶部窗口无法移动的问题。在Windows和macOS中都有出现。经过试验，只有在左上角会员图标处的小区域可以点击移动窗口。
![image](https://user-images.githubusercontent.com/30540766/196378461-e95a3c33-8674-40f6-b1dc-914099e58239.png)

**Comment by svchord** [comment]
最新版已修改并上传，顶栏除了按钮以外的区域都可以拖拽窗口，请等待集市打包上架或自行下载最新发布版本使用
