### ISSUE TITLE
被引次数的标识似乎有点问题

### ISSUE THREAD

**Issue by SsparKluo** [svchord/Rem-Craft#51]
![image](https://user-images.githubusercontent.com/32617864/197376964-d42725d7-74f4-4c87-b4ae-68fa9155a845.png)
这个挡住了原本的段落。
![image](https://user-images.githubusercontent.com/32617864/197377002-cab4024e-d789-49f9-a05b-a0054bbc5f43.png)
这个挡住了命名/别名。

**Comment by SsparKluo** [comment]
BTW，不知道作者大大有没有兴趣参考下隔壁notion的悬浮状态栏之类的

**Comment by svchord** [comment]
1. 已修复，请等待版本更新
2. notion主题是把 `隐藏边栏` 按钮融入边栏，不适合我的主题，所以在无法解决这个按钮的情况下，无法将其他按钮的样式直接抄过来。我目前没想到怎么搞，你有什么解决的建议吗？

**Comment by SsparKluo** [comment]
![image](https://user-images.githubusercontent.com/32617864/197431763-63e70d89-d10b-4e46-bc41-df09dfdba816.png)
不知道把 隐藏边栏按钮 安排在这个位置可不可以？

**Comment by svchord** [comment]
css只能做到以屏幕四角为原点确定位置，放在这里的话，移动分割线的时候，这个按钮不会跟着移动，看起来会很奇怪

**Comment by SsparKluo** [comment]
想了想，确实是不太好处理。
还有个小问题，
![image](https://user-images.githubusercontent.com/32617864/197436253-6099fec3-f645-4016-817e-f387a130c45c.png)
![image](https://user-images.githubusercontent.com/32617864/197436258-9486ec08-7d02-4f28-bf86-072ea2a9c957.png)
这两个菜单的位置没有对齐。

**Comment by svchord** [comment]
这个不是bug，主要是为了解决帮助按钮悬浮菜单很难点到的问题，所以把菜单下移了

**Comment by SsparKluo** [comment]
这样！还有一点小问题
![image](https://user-images.githubusercontent.com/32617864/197448184-f5751b3f-77c0-4d02-b2e2-3bec4cc932cc.png)
这个备注，因为引用的样式的边框是圆角，所以和普通的文本会有割裂

**Comment by svchord** [comment]
我这边不是圆角，你看看是不是缓存问题

**Comment by SsparKluo** [comment]
删掉重新下载了一遍，似乎还是圆角？
![image](https://user-images.githubusercontent.com/32617864/197452785-0f89caf2-106d-4af6-a8cb-c8e15592688c.png)
不过这个问题感觉不太重要..毕竟同时备注普通文本和引用挺难用的。

**Comment by svchord** [comment]
啊，原来你是说同时备注和引用啊，那确实没改过，不过像你说的那样，也没必要改了

**Comment by SsparKluo** [comment]
> 1. 已修复，请等待版本更新
> 2. notion主题是把 `隐藏边栏` 按钮融入边栏，不适合我的主题，所以在无法解决这个按钮的情况下，无法将其他按钮的样式直接抄过来。我目前没想到怎么搞，你有什么解决的建议吗？

![image](https://user-images.githubusercontent.com/32617864/200162643-9c6328ab-cb55-4f0a-8aa3-b105a1570f6b.png)
我觉得加到这个list里应该可以？

我自己是用代码片段加到这里了，似乎没什么问题
![image](https://user-images.githubusercontent.com/32617864/200162670-ff9146b6-2d44-4ce6-acea-9446419689b6.png)

**Comment by svchord** [comment]
请教一下怎么改的，能贴一下代码片段就更好了

**Comment by SsparKluo** [comment]
基本上就是借用的 notion-theme 里的代码（CSS 都是直接用的 notion-theme 的）
```js
function loadStyle(url, id, cssName) {
    var headElement = document.head;

    let style = document.getElementById(id);
    if (id != null) {
        if (style) headElement.removeChild(style);
    }

    style = document.createElement("link");
    if (id != null) style.id = id;

    style.setAttribute("type", "text/css");
    style.setAttribute("rel", "stylesheet");
    style.setAttribute("href", url);
    if (cssName != null) style.setAttribute("class", cssName);
    headElement.appendChild(style);
    return style;
}

function addButton() {
    var buttonList = document
        .getElementById("barHelp")
        .getElementsByTagName("div")[0];
    var buttonElement = document.createElement("button");
    buttonElement.id = "hide_left_column";
    buttonElement.setAttribute("class", "b3-menu__item");
    buttonList.appendChild(buttonElement);
    buttonElement.innerHTML =
        "<svg class='b3-menu__icon'><use xlink:href='#iconLeft'></use></svg><span class='b3-menu__label'>隐藏左侧菜单</span>";

    var offNo = localStorage.getItem("hide_left_column");
    if (offNo == "1") {
        loadStyle(
            "/appearance/themes/notion-theme/style/topbar/leftcolumn.css",
            "leftColumn悬浮"
        ).setAttribute("topBarcss", "leftColumn悬浮");
        localStorage.setItem("hide_left_column", "1");
        var btn = document.getElementById("hide_left_column");
        btn.removeAttribute("class");
        btn.setAttribute("class", "b3-menu__item b3-menu__item--selected");
    } else if (offNo != "0") {
        localStorage.setItem("hide_left_column", "0");
        document.getElementById("leftColumn悬浮").remove();
        localStorage.setItem("hide_left_column", "0");
        btn.removeAttribute("class");
        btn.setAttribute("class", "b3-menu__item");
    }

    buttonElement.addEventListener("click", () => {
        var offNo = localStorage.getItem("hide_left_column");
        var btn = document.getElementById("hide_left_column");
        if (offNo == "0") {
            loadStyle(
                "/appearance/themes/notion-theme/style/topbar/leftcolumn.css",
                "leftColumn悬浮"
            ).setAttribute("topBarcss", "leftColumn悬浮");
            localStorage.setItem("hide_left_column", "1");
            btn.removeAttribute("class");
            btn.setAttribute("class", "b3-menu__item b3-menu__item--selected");
            offNo = "1";
            return;
        }

        if (offNo == "1") {
            document.getElementById("leftColumn悬浮").remove();
            localStorage.setItem("hide_left_column", "0");
            btn.removeAttribute("class");
            btn.setAttribute("class", "b3-menu__item");
            offNo = "0";
            return;
        }
    });
}

addButton();
```

没怎么写过 js 和 css，应该有不少可以改进的lol

**Comment by svchord** [comment]
js对我来说也有点困难，而且看里面还引用了notion-theme的css文件，我慢慢试着改吧，先发个版

**Comment by SsparKluo** [comment]
简单的js，像是添加按钮之类的，我倒是可以帮忙写 ... 不过css我是真心不会了，所以就直接用了notion-theme的css

**Comment by SsparKluo** [comment]
话说..新的版本似乎性能有一点问题？滚动起来卡卡的，打开设置的动画也不太顺滑

**Comment by svchord** [comment]
这些应该不是主题的问题，我应该只是在打开边栏的动画有问题…

**Comment by SsparKluo** [comment]
emm...用其他主题的时候似乎没有问题

**Comment by svchord** [comment]
最新版已修改并上传，请等待集市打包上架或自行下载仓库到主题文件夹使用
