### ISSUE TITLE
关于分屏显示时顶部页签栏的一点建议

### ISSUE THREAD

**Issue by intelion2022** [svchord/Rem-Craft#52]
很喜欢RC这个主题，简洁、大气、逻辑显示更清晰，只有一点不习惯，就是分屏显示时顶部标签虽页签面板而变化，很容易错乱，经常搞错，希望分屏时各自栏的页签独立，像obsidian那样。谢谢！

**Comment by svchord** [comment]
目前我的技术不足以做到这一点，抱歉

**Comment by svchord** [comment]
没想到过了一晚上，我就想到怎么解决了…请等待版本更新

**Comment by svchord** [comment]
最新版已修改并上传，请等待集市打包上架或自行下载最新发布版本使用
