### ISSUE TITLE
模态框样式

### ISSUE THREAD

**Issue by allynlin** [svchord/Rem-Craft#53]
关于模态框，有没有可能参考 Windows11 做一下云母效果或者亚克力效果的适配，又或者支持一下 CSS3 的 backdrop-filter 如果可以自定义模糊半径，饱和度，蒙版会更好。

**Comment by svchord** [comment]
纯css无法做到适配win的云母或亚克力材质，只有用winui3开发的软件才能做到。

我也看过有个项目用 backdrop-filter模拟实现的效果，但说实话质感很差。如果你有推荐，可以发一下仓库链接。

**Comment by svchord** [comment]
纯css无法做到适配win的云母或亚克力材质，只有用winui3开发的软件才能做到。

我也看过有个项目用 backdrop-filter模拟实现的效果，但说实话质感很差。如果你有推荐，可以发一下仓库链接。

**Comment by allynlin** [comment]
目前来说，我实现模拟亚克力效果是这么写的
`
background-color: rgba(255, 255, 255, 0.5);
backdrop-filter: blur(20px) saturate(180%);
-webkit-backdrop-filter: blur(20px) saturate(180%);
`
但是这个肯定不是所有人都会喜欢，有没有一种可能自定义模态框的 CSS，就可以自己对模态框 CSS 做修改

**Comment by svchord** [comment]
我没太理解你后面那段话，css本来就是用来自定义的啊，你把你的样式写在`theme.css`的末尾不就行了

**Comment by svchord** [comment]
至于前面那个亚克力效果…只能说十分不适合我的主题
