### ISSUE TITLE
菜单在最顶上的次级菜单中与标签页重合的选项无法点击

### ISSUE THREAD

**Issue by SsparKluo** [svchord/Rem-Craft#54]
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/32617864/197923937-c45f435c-84d8-4f6a-9375-cd6c7ee1a194.png">

就这个 `转换为` 的 `无序列表` 点不了，默认主题是让菜单避开这个区域。

**Comment by svchord** [comment]
我没能复现这个问题，请下个版本更新后看看

**Comment by SsparKluo** [comment]
更新了，还是有问题。
![动画2](https://user-images.githubusercontent.com/32617864/198442928-2b45a30e-4ddd-4f4d-a1a1-ec1098c4c0a4.gif)

**Comment by svchord** [comment]
复现了，并且已修复，请等下个版本更新
