### ISSUE TITLE
页面标签到后面不显示关闭按钮了？

### ISSUE THREAD

**Issue by intelion2022** [svchord/Rem-Craft#57]
![image](https://user-images.githubusercontent.com/116488969/198877580-ae856443-7d24-4c25-96d9-63c887c92630.png)

**Comment by svchord** [comment]
可以左右滚动啊，这是默认主题也有的功能

**Comment by intelion2022** [comment]
请教，怎么操作来实现滚动？

**Comment by svchord** [comment]
就是鼠标移到页签栏区域，然后用鼠标滚轮或者触摸屏双指滚动

**Comment by intelion2022** [comment]
嗯嗯，学习了，谢谢~
