### ISSUE TITLE
关于改进引述块显示效果的建议

### ISSUE THREAD

**Issue by intelion2022** [svchord/Rem-Craft#58]
主题中引述块左侧细黑线，显得突兀，感觉和主题整体风格不太相符，建议左侧竖线颜色和引述块文字颜色一致，同时线可加粗一些。下面提供wolai和Obsidian引述块显示效果，供参考：
![2022-10-30_202643](https://user-images.githubusercontent.com/116488969/198878901-9fbdbe3c-2356-4f1f-976c-87cdb699a877.jpg)
![2022-10-30_202605](https://user-images.githubusercontent.com/116488969/198878903-1327541c-1dca-422d-a5ae-64ffcf2b2320.jpg)

**Comment by svchord** [comment]
额，我就是参考obsidian的样式啊，只不过改了颜色

**Comment by intelion2022** [comment]
黑色太突兀了，和文字一样的灰色好一些

**Comment by svchord** [comment]
和正文文字一样的颜色，引述块内的文字颜色是故意调淡了的

**Comment by intelion2022** [comment]
视觉效果上比正文颜色要深
![0F9E3746](https://user-images.githubusercontent.com/116488969/198879352-dec3137a-8e35-46cc-a5f6-7da3210c6591.png)

**Comment by svchord** [comment]
下个版本我把引述块也改成正文颜色试试吧

**Comment by svchord** [comment]
最新版已修改并上传，请等待集市打包上架或自行下载最新发布版本使用

**Comment by intelion2022** [comment]
感觉还是把那条竖线颜色变浅一些好看，个人意见，仅供参考~
![image](https://user-images.githubusercontent.com/116488969/199731520-48fd4703-720b-4c29-8fc3-7dcd136ff710.png)

**Comment by svchord** [comment]
你可以使用代码片段功能添加如下css：

```css
.b3-typography blockquote::after,
.protyle-wysiwyg .bq::after{
  background-color: 你要的颜色;
}
```

**Comment by intelion2022** [comment]
谢谢大佬，这下可以使用自己喜欢的颜色啦
![00194A5D](https://user-images.githubusercontent.com/116488969/200793557-778238d7-3ad4-44c0-ab1a-6baf5edc3036.png)
