### ISSUE TITLE
一个小问题，左下角的同步信息会挡住“已关闭的笔记”

### ISSUE THREAD

**Issue by komoechan** [svchord/Rem-Craft#59]
如图，不是什么大问题，但是微妙的有点影响美观度
![遮挡](https://user-images.githubusercontent.com/66232948/199640417-efbd475d-1864-40f4-a02b-3af67a01ca14.png)

**Comment by svchord** [comment]
最新版已修改并上传，请等待集市打包上架或自行下载最新发布版本使用
