### ISSUE TITLE
标签显示的一个小瑕疵

### ISSUE THREAD

**Issue by intelion2022** [svchord/Rem-Craft#60]
标签刚好遇到换行时，#会留在上一行，建议把“#”和标签文字作为一个整体，在标签遇到换行时进行整体换行。

![image](https://user-images.githubusercontent.com/116488969/199730618-ef5560e9-0bc3-456f-af6b-7bd53f7bb06e.png)

**Comment by svchord** [comment]
最新版已修改并上传，请等待集市打包上架或自行下载最新发布版本使用
