### ISSUE TITLE
建议：文档树面板行间距适当缩小

### ISSUE THREAD

**Issue by intelion2022** [svchord/Rem-Craft#62]
文档树，包括右侧的大纲面板、反链面板行间空白相较于其他主题明显偏大，建议可适当缩小30%左右，这样既可保持咱们这个主题清新的风格，又可以容纳更多信息。
![image](https://user-images.githubusercontent.com/116488969/200149914-38f61711-1a3c-42a4-bfab-040cd9079c41.png)

**Comment by svchord** [comment]
最新版已修改并上传，请等待集市打包上架或自行下载最新发布版本使用
