### ISSUE TITLE
建议将右侧的块条淡化处理一下

### ISSUE THREAD

**Issue by GH-W94** [svchord/Rem-Craft#63]
![image](https://user-images.githubusercontent.com/117154557/200236130-d859278c-520a-41cd-ae39-08411f868532.png)
建议将右侧的块条淡化处理一下，整个编辑的界面是白色的，而块条是加粗、颜色深色的，这样太吸引注意力了，所以建议将其淡化处理，颜色变浅，线条变细。

**Comment by svchord** [comment]
这个是和其他界面里的进度条共用样式的…我之后想想怎么改，如果你有什么现成想法也可以发一下代码片段

**Comment by svchord** [comment]
最新版已修改并上传，请等待集市打包上架或自行下载仓库到主题文件夹使用

**Comment by GH-W94** [comment]
> 最新版已修改并上传，请等待集市打包上架或自行下载仓库到主题文件夹使用

感谢大佬
