### ISSUE TITLE
feat：为非最大化窗口添加一个窗口边框

### ISSUE THREAD

**Issue by Reverier-Xu** [svchord/Rem-Craft#64]
没有边框和窗口阴影的时候，很容易和其他配色相似的窗口融为一体。但是窗口阴影要求不同平台均支持electron背景透明化，在不支持的平台上观感会很差，所以建议为非最大化窗口添加一个1px的细边框，这样看起来舒服一些。

![image](https://user-images.githubusercontent.com/41937333/200309496-780cbd57-e97e-4a88-a5ff-e454ec3915fc.png)

**Comment by svchord** [comment]
非最大化好像没有专门的选择器，窗口失去焦点时添加行不行？

**Comment by Reverier-Xu** [comment]
可以添加一个js来实现这个？

我实现一下试试，没问题的话我提一个pr

**Comment by svchord** [comment]
辛苦了，已合并
