### ISSUE TITLE
打开文章之后tab-bar将tool-bar按钮挡住

### ISSUE THREAD

**Issue by Reverier-Xu** [svchord/Rem-Craft#67]
![image](https://user-images.githubusercontent.com/41937333/201037428-1f0c4107-28a2-45a0-b261-8d334c444bb5.png)

如图所示，开启左侧dock的时候左边工具栏按钮还是可点的，不开启的时候上面的tab-bar就将下面的工具栏按钮覆盖住了，能看见但是无法点击。

右侧边栏由于我不开所以右上角的工具栏按钮一直是被遮挡点击的，只有关闭所有文章之后才能点击。右侧这个margin也不太够，把搜索按钮挡住了：

![Screenshot_20221110_161826](https://user-images.githubusercontent.com/41937333/201038355-275e68bc-f221-40fa-a0fe-2a7efefa29b1.png)

**Comment by svchord** [comment]
是z-index导致的，思源之前的版本是可以的，最新的不行，我下个版本改，你可以先用代码片段顶顶：

```css
#toolbar .toolbar__item{
    z-index:9;
}
```

**Comment by svchord** [comment]
最新版已修改并上传，请等待集市打包上架或自行下载仓库到主题文件夹使用

**Comment by Reverier-Xu** [comment]
![image](https://user-images.githubusercontent.com/41937333/204229870-f78bbc1e-e7b9-477f-8ab7-4f9bbf0c994e.png)

问题似乎仍旧存在？思源笔记版本与主题版本均已更新

**Comment by svchord** [comment]
你是什么系统？windows系统的日历按钮应该在左边。但你却又有win系统的三个按钮

**Comment by Reverier-Xu** [comment]
Arch Linux 下的 KDE Plasma 5.26.3

**Comment by svchord** [comment]
是我疏忽了……

你可以找到`plugin/tabBar/main.js`文件的第127行：

`: btnWidth * 6 + 2;`

改为

`: btnWidth * 6 + winBtnsWidth - dockWidth`

然后重启即可，先这样顶顶，等我下个版本搞好兼容

**Comment by svchord** [comment]
如果有空的话，麻烦帮忙看看linux系统环境下，右上角三个按钮组的id是不是也叫`windowControls`

**Comment by svchord** [comment]
最新版已修改并上传，请等待集市打包上架或自行下载仓库到主题文件夹使用
