### ISSUE TITLE
建议引入Savor主题的日历功能

### ISSUE THREAD

**Issue by intelion2022** [svchord/Rem-Craft#69]
![image](https://user-images.githubusercontent.com/116488969/201503678-4c63b783-c142-4c60-951c-b662e862c81f.png)

**Comment by svchord** [comment]
能力有限，要等挺久了

**Comment by intelion2022** [comment]
这个可以等
![15708660](https://user-images.githubusercontent.com/116488969/201522873-565ba936-a50a-41a1-87a3-4e587c24bca9.png)

**Comment by svchord** [comment]
最新版已修改并上传，请等待集市打包上架或自行下载仓库到主题文件夹使用
