### ISSUE TITLE
建议插入的文件前面显示页面类型图标

### ISSUE THREAD

**Issue by intelion2022** [svchord/Rem-Craft#70]
![image](https://user-images.githubusercontent.com/116488969/201503792-f18f736b-3427-4e33-b4cb-eff6b86682f3.png)

**Comment by svchord** [comment]
页面类型图标是什么意思？

**Comment by zhanganchi352242** [comment]
可能就是它红框框柱的图标
例如他给的图中链接对应 Word 文档，就会有这个“蓝色的纸 + W 字母”的 logo
再例如b站视频链接会有小电视
咱现在至少 Word 文档是没有图标的
![image](https://user-images.githubusercontent.com/50255967/201520898-f5a6d803-1143-44f4-b523-af07f08f459c.png)

**Comment by intelion2022** [comment]
可能表述不太准确，应该叫文件类型图标，比如插入的Word、pdf等文件分别显示对应图标，就像在资源管理器中那样~下面是在savor主题中的效果：
![image](https://user-images.githubusercontent.com/116488969/201522833-aad57ffe-087c-43ac-a538-febf75e020e7.png)

**Comment by svchord** [comment]
不对啊，应该是有的，因为我和savor都抄的dark+…可能我哪里写错了，之后去看看

**Comment by svchord** [comment]
最新版已修改并上传，请等待集市打包上架或自行下载仓库到主题文件夹使用
