### ISSUE TITLE
希望点三角左侧也可以展开子文件列表

### ISSUE THREAD

**Issue by zhanganchi352242** [svchord/Rem-Craft#71]
现在点三角左侧无法展开子文件列表，由于双击展开子文档列表被取消，只能点三角很容易误触或点不中。
![无法点三角左侧展开子文件列表](https://user-images.githubusercontent.com/50255967/201504410-be194ea7-d90d-40f9-b74c-52ba2903da00.gif)
希望可以像默认主题一样点三角左侧也可以展开子文件列表
![默认主题可以点三角左侧展开子文件列表](https://user-images.githubusercontent.com/50255967/201504421-342b5a74-55c9-4ff9-aa32-404236db026e.gif)

**Comment by svchord** [comment]
如果要实现这种效果的话，文档树上的辅助线可能就无法显示了，我之后会把这个功能抽出来，做个开关

**Comment by svchord** [comment]
最新版已修改并上传，请等待集市打包上架或自行下载仓库到主题文件夹使用。

更新后，可以把`script/config.js`中的`listIndent`值修改为`false`，取消文档树缩进和辅助线。
