### ISSUE TITLE
特殊状态栏挡住提及的展开、刷新等按钮

### ISSUE THREAD

**Issue by zhanganchi352242** [svchord/Rem-Craft#75]
如下图，正好挡得死死的，有点难绷
![image](https://user-images.githubusercontent.com/50255967/203457740-f80bc570-6bab-4047-a861-9006984c20e0.png)

**Comment by itachaaa** [comment]
+1 正想提；我是把大纲放在右边，刚好挡住最下面的标题，不过影响还不是很大 哈哈哈；

**Comment by svchord** [comment]
最新版已修改并上传，请等待集市打包上架或自行下载仓库到主题文件夹使用
