### ISSUE TITLE
关于在代码片段中引用子弹线样式

### ISSUE THREAD

**Issue by winter60** [svchord/Rem-Craft#78]
大佬，你的子弹线样式太牛逼了，太惊艳了，🚀🎈❤️，就是不知道能否做一个代码片段版本方便任意主题使用呢？我尝试引用`Rem Craft\plugin\bullet\main.css` 和`Rem Craft\plugin\bullet\main.js`但不生效，不知道是不是scss的缘故，不太会引用。请大佬指点一下~

**Comment by svchord** [comment]
引用`main.css`的时候把css变量改成自己需要的，比如`var(--text-brand)`就是子弹线的颜色，`rgba(var(--border-1))`是待办列表完成后的子弹线颜色。然后在`main.js`的末尾，加一行`bulletMain();`即可。

**Comment by winter60** [comment]
谢谢老大，已解决~
