### ISSUE TITLE
大佬可以优化下吗，太卡了

### ISSUE THREAD

**Issue by masj56** [svchord/Rem-Craft#79]
这个主题颜色风格搭配很nice啊，但是切换后对比其他主题特别的卡，麻烦大佬有空了优化下吧，如gif对比。而且偶发性看不到内容，这个还没找到规律。
![theme](https://user-images.githubusercontent.com/17619676/204186829-18af69a4-70b3-4aaa-b7e3-944091be18b4.gif)
![theme2](https://user-images.githubusercontent.com/17619676/204186849-18b5c25c-72a0-4c21-be5b-cc27e0cff5bf.gif)

**Comment by svchord** [comment]
我这里没能复现你的问题，要不下载仓库最新版试试？集市太久不更新了

**Comment by masj56** [comment]
> 我这里不能复现你的问题，要不要下载仓库最新版试试？集市太久没更新了

刚才切换主题的时候出现了内容直接看不到的问题，关掉再打开就又好了，就是最新的呀，确实我这边感觉会很卡，我是19年的i9的mac，难道是我电脑太旧了。。

**Comment by masj56** [comment]
> 我这里不能复现你的问题，要不要下载仓库最新版试试？集市太久没更新了

刚才切换主题时候出现了标签页的文件的内容看不到了，关闭标签页再打开就能看到了。
我这边是最新的啊，感觉对比其他的主题确实卡了很多，我是19年的i9的macbook pro.

**Comment by svchord** [comment]
先确认下主题和思源的版本是不是都是2.5.1？我这边确实没啥问题，包括切换主题，我知道的另外一个mac用户也没提过这个问题…

**Comment by svchord** [comment]
![页签变化](https://user-images.githubusercontent.com/61345763/204190853-87ca5581-f875-4ce2-8742-52c6d27465ed.gif)

你看，我这边是这样

**Comment by svchord** [comment]
有定位到问题吗？

**Comment by svchord** [comment]
你好，有定位到问题来源吗？是版本问题，还是操作系统不兼容的特殊情况？

**Comment by masj56** [comment]
> 你好，有定位到问题来源吗？是版本问题，还是操作系统不兼容的特殊情况？

还没有追着继续看，最近工作事情有点多，我周六周日再试试看看，目前我体验确实是切到这个主题就明显卡顿了。。。

**Comment by svchord** [comment]
> 还没有追着继续看，最近工作事情有点多，我周六周日再试试看看，目前我体验确实是切到这个主题就明显卡顿了。。。

好的，之后有空的话可以尝试修改`script/config.js`文件，帮忙定位一下是哪部分的问题

**Comment by SsparKluo** [comment]
确实有点卡...感觉要是要优化的话工作量会不小

**Comment by xy0124** [comment]
我也有这样的体验
每次切换到该主题，浏览起来感觉就费劲一些，没有那种顺畅感。同时电脑的占有率也会增加一点。

**Comment by svchord** [comment]
@SsparKluo @xy0124 请问你们碰到的是上面gif里那种页签栏频闪的问题，还是浏览时卡顿的问题？

**Comment by SsparKluo** [comment]
> @SsparKluo @xy0124 请问你们碰到的是上面gif里那种页签栏频闪的问题，还是浏览时卡顿的问题？如果通过config.js关闭特殊功能，是否会有好转？

是常规浏览的时候卡顿（之前已经有反馈过了，现在更严重了其实）
似乎设置为 false 并没有用，用开发者工具 disable javascript 之后确实是要流畅不少。但是如果用 performance 来看，似乎渲染瓶颈比较严重。
![image](https://user-images.githubusercontent.com/32617864/204771138-1cb194ba-5b78-4d31-b3b9-bd93e73a4ec4.png)

**Comment by svchord** [comment]
> 是常规浏览的时候卡顿（之前已经有反馈过了，现在更严重了其实） 似乎设置为 false 并没有用，用开发者工具 disable javascript 之后确实是要流畅不少。

明白了，可能是监听器写太多导致的，但我不太懂mutationobserver怎么搞事件委托……我去查查好了

**Comment by SsparKluo** [comment]
> > 是常规浏览的时候卡顿（之前已经有反馈过了，现在更严重了其实） 似乎设置为 false 并没有用，用开发者工具 disable javascript 之后确实是要流畅不少。
> 
> 明白了，可能是监听器写太多导致的，但我不太懂mutationobserver怎么搞事件委托……我去查查好了

对了，
>似乎设置为 false 并没有用

指的是设置为 false 之后，重启之后，该加载功能的还是加载了，似乎和true没什么区别。
我记得 mutationobserver 好像可以指定监听具体的变动？

**Comment by svchord** [comment]
> 指的是设置为 false 之后，重启之后，该加载功能的还是加载了，似乎和true没什么区别。

会不会是缓存问题？我刚刚试了下是可以的

> 我记得 mutationobserver 好像可以指定监听具体的变动？

作为一个js菜鸟，我只知道可以监听属性、子元素和子树的变动，但是子树的变动会更频繁地触发，我不敢用，可是不用的话又不能搞事件委托……

**Comment by svchord** [comment]
> 我是常规浏览，就是感觉滚轮滚动特别费劲那种感觉。明显相对于默认和notion主题来说，少了顺畅感。

我突然想到，如果是常规浏览的话，可能不是主题的问题，因为我没有在编辑器内部修改太多样式，更没有加很多监听器啊

**Comment by SsparKluo** [comment]
> > 我是常规浏览，就是感觉滚轮滚动特别费劲那种感觉。明显相对于默认和notion主题来说，少了顺畅感。
> 
> 我突然想到，如果是常规浏览的话，可能不是主题的问题，因为我没有在编辑器内部修改太多样式，更没有加很多监听器啊

嗯...更大的可能是样式太多，渲染不过来。这个问题在出现不同样式的块（比如列表）的时候比较明显

**Comment by svchord** [comment]
> 嗯...更大的可能是样式太多，渲染不过来。这个问题在出现不同样式的块（比如列表）的时候比较明显

我看了下，和编辑器内部块有关的样式只有1k行左右，不到theme.css的1/5……

你们行内超链接用得多吗？我不清楚是不是超链接图标的原因，但按理说dark+和savor也有这个功能，应该与此无关才对。

**Comment by SsparKluo** [comment]
应该不是icon的问题...不如我发一个在我这边卡到不行的文档给你试试？

**Comment by svchord** [comment]
> 应该不是icon的问题...不如我发一个在我这边卡到不行的文档给你试试？

好的

**Comment by SsparKluo** [comment]
@xy0124 可以去 `config.js` 里把 `tabBar` 设置为 `false`，应该可以暂时解决问题。

**Comment by xy0124** [comment]
> > 我是常规浏览，就是感觉滚轮滚动特别费劲那种感觉。明显相对于默认和notion主题来说，少了顺畅感。
> 
> 我突然想到，如果是常规浏览的话，可能不是主题的问题，因为我没有在编辑器内部修改太多样式，更没有加很多监听器啊

具体我不懂，就是对比才发现。我切换到自带主题和notion主题，就很顺畅。

**Comment by svchord** [comment]
等新版看看怎么样

**Comment by xy0124** [comment]
反馈：新版更新后，浏览顺畅很多了。很赞改进的方向、

**Comment by svchord** [comment]
> 6. 再次设置外观主题为跟随系统，此时出现内容消失的问题

请问系统是暗黑还是明亮？我这边按照这个步骤并没有复现出这个问题……

**Comment by svchord** [comment]
将系统设置为暗黑后成功复现了，但这个问题显然并不是我的主题的问题，因为消失的原因是`.protyle`元素添加了`.fn__none`选择器，而我并没有进行过这种操作…我建议还是提给官方吧

**Comment by masj56** [comment]
> 

奥，忘了说了，我电脑默认是暗黑模式

**Comment by masj56** [comment]
> 将系统设置为暗黑后成功复现了，但这个问题显然并不是我的主题的问题，因为消失的原因是`.protyle`元素添加了`.fn__none`选择器，而我并没有进行过这种操作…我建议还是提给官方吧

思源的问题吗，我换个主题试下，还没拿别的试过呢

**Comment by svchord** [comment]
> 思源的问题吗，我换个主题试下，还没拿别的试过呢

嗯，我用dark+也复现成功了，我猜应该是复杂主题都会有这种问题，建议提给官方，不过这么复杂的操作一般用户也不会做，官方会不会改就不清楚了

**Comment by masj56** [comment]
> 将系统设置为暗黑后成功复现了，但这个问题显然并不是我的主题的问题，因为消失的原因是`.protyle`元素添加了`.fn__none`选择器，而我并没有进行过这种操作…我建议还是提给官方吧

确实，别的主题这样切换也会是这样，看来是思源的问题了，这还是我之前挑主题来回切发现的，还以为是主题的问题呢。另外我今天更新后体验比之前丝滑多了，感谢感谢！
