### ISSUE TITLE
列表子弹流辅助线对得不是很齐

### ISSUE THREAD

**Issue by zhanganchi352242** [svchord/Rem-Craft#80]
如下图，能否让线条插到圆点圆心，而不是这样似乎是有点相切的感觉
![image](https://user-images.githubusercontent.com/50255967/204337115-057c48eb-55f0-4b60-b693-b5c00356fb5d.png)
如果是设计如此的话，不好意思打扰了

**Comment by svchord** [comment]
![image](https://user-images.githubusercontent.com/61345763/204337882-d14c2872-a292-49a1-93bb-1d6ad7aeeb88.png)

肯定不是设计如此，我这里是这样……我猜是其他代码片段导致的问题

**Comment by zhanganchi352242** [comment]
确实，我参考[这篇帖子](https://ld246.com/article/1666932416932)用代码片段调整了列表缩进和列表行间距
那我这边就只能这样喽？

**Comment by svchord** [comment]
我看了眼代码片段，尺寸单位不同，要兼容的话要改很多地方，我建议二选一。另外，其实前三到四个层级可以用标题的，毕竟是文档笔记

**Comment by svchord** [comment]
对了提醒一下，子弹线是可以通过`script/config.js`文件关掉的

**Comment by zhanganchi352242** [comment]
好嘞，config.js 我晓得的，作者大大辛苦了

**Comment by svchord** [comment]
版本更新上传了，没别的问题我就先关了
