### ISSUE TITLE
有序列表子弹流辅助线异常

### ISSUE THREAD

**Issue by zhanganchi352242** [svchord/Rem-Craft#81]
不好意思，只是想看看有序列表的效果就有发现了新 Bug
如下图，子弹流辅助线去找上边的列表了
![image](https://user-images.githubusercontent.com/50255967/204337925-f93b4fcf-124f-4f3f-998b-1414ca84a7ac.png)
不过好像其实是有序列表的辅助线会去找列表符号的最顶端？
![image](https://user-images.githubusercontent.com/50255967/204338190-ecd5792f-bd15-4e1c-8af2-99c746a439db.png)

**Comment by zhanganchi352242** [comment]
对，就是创造有序列表后直接继续创造无序列表时会有这个问题
![image](https://user-images.githubusercontent.com/50255967/204341113-6af2f6b5-0bb0-4c53-a020-9ec747474bbd.png)
![image](https://user-images.githubusercontent.com/50255967/204341156-1e9c051d-b91c-4fba-985d-266de4c579e0.png)
想了想偶尔可能会这样用，会改嘛？

**Comment by svchord** [comment]
应该不会改了，毕竟使用场景太少，而且靠css改肯定不行，靠js改需要很长时间

**Comment by zhanganchi352242** [comment]
好嘞，既然麻烦就不折腾了，辛苦作者大大了！

**Comment by svchord** [comment]
版本更新上传了，没别的问题我就先关了
