### ISSUE TITLE
顶栏页签异常

### ISSUE THREAD

**Issue by zhanganchi352242** [svchord/Rem-Craft#82]
如图，新建日记后按 Alt + 1 缩回文档树，页签就跟着缩到左边了，然后顶栏的所有按钮都用不了，是我 alt + p 打开设置重置外观后才恢复，但恢复后每次都能复现
![image](https://user-images.githubusercontent.com/50255967/204448712-ce93fa18-ea1e-4795-b207-99c55e77282d.png)
思源是最新版，主题是集市最新版，Win 11

**Comment by svchord** [comment]
有没有试过重启？目前顶栏页签出现问题重置外观是大概率没有作用的，一般是重启。

如果重启还是没有效果，我再看看是怎么回事，目前我这边没能复现

**Comment by zhanganchi352242** [comment]
重启思源状况相同，甚至还多了重叠图标
![image](https://user-images.githubusercontent.com/50255967/204450023-978b3140-d7c2-48fd-8fe3-6f157be0375f.png)
接下来让我试试重启电脑

**Comment by svchord** [comment]
重启电脑肯定是没用的

**Comment by zhanganchi352242** [comment]
![image](https://user-images.githubusercontent.com/50255967/204451174-fcf0195b-806c-455c-a5ec-f238823a2bd5.png)
集市里更新按钮看不见我知道的，确认是最新版、
开发者工具有这么个异常
![image](https://user-images.githubusercontent.com/50255967/204451253-30fc9dfb-50bb-41eb-b417-d1f830158335.png)

**Comment by svchord** [comment]
这个异常不是我的主题js抛出来的，这我就真搞不懂了…

![image](https://user-images.githubusercontent.com/61345763/204451641-256a1680-2e6b-4ee0-a033-67683ea0135b.png)

另外你没记错，我这边现在就是这样的，所以感觉摸不着头脑

![image](https://user-images.githubusercontent.com/61345763/204451738-a54450d5-0f16-4c48-b3fa-00d26d8541f7.png)

要不把代码片段关掉试试？

**Comment by zhanganchi352242** [comment]
不行，所有代码片段都关了，重启思源，还是一样
（好在默认主题是好的

**Comment by svchord** [comment]
那就真的不清楚了，可能是其他主题的什么缓存影响了，但按理说应该不会……

最后在开发者工具输入`document.getElementsByClassName("rc-tabBar-left")[0]`然后回车，看看能不能获取到吧

**Comment by zhanganchi352242** [comment]
看起来没能收获好的反应
![image](https://user-images.githubusercontent.com/50255967/204455056-a77a1591-77aa-43e3-bd28-307824a07874.png)

**Comment by svchord** [comment]
那就是js完全没有工作了，建议重装主题，还不行的话，就只能通过config.js把顶部页签栏这个功能关掉了

**Comment by zhanganchi352242** [comment]
卸载，重启思源，重装主题，无效
改 config.js，倒是能用，就启动页面还是有点抽象
![image](https://user-images.githubusercontent.com/50255967/204457323-67bdc88c-9322-4dc5-8923-0c8d39716c6a.png)
![image](https://user-images.githubusercontent.com/50255967/204457446-e08ee9c5-6a53-4dad-8e94-65987ece46bf.png)

**Comment by svchord** [comment]
啊，这个启动界面我还真忘了改，你可以先用下面的代码片段顶顶：

```css
.layout__center:has(.layout__empty){
   padding-top:0;
}
```

顺便帮我测测关掉之后能不能正常使用，你也麻烦了

**Comment by zhanganchi352242** [comment]
这个片段可以改掉启动页面的问题，
然后 config 关掉以后，测试了打开页签、钉住页签、alt 快捷键开关文档树大纲树反链面板、重启思源都没遇到问题

**Comment by svchord** [comment]
ok那就好，等过段时间你有空再打开试试，可能会玄学地自己好了，因为我感觉怎么找不到问题所在这件事也挺玄学的……

**Comment by zhanganchi352242** [comment]
哈哈，代码就是这样，玄学地不得了

**Comment by zhanganchi352242** [comment]
v2.5.3 问题依旧

**Comment by svchord** [comment]
2.5.4看看怎么样

**Comment by zhanganchi352242** [comment]
噢不对，也没有完全正常，现在第一次打开日记时顶部页签会卡一下，然后页签下面会有你说过不应该出现的横线，后面就正常了。
但按 alt + 1 开关文档树时确实是不会缩回页签了。
![RemCraft Bug反馈](https://user-images.githubusercontent.com/50255967/205844747-76759676-5666-476d-83b1-8147e6cc8607.gif)
只能说确实是不影响使用了。

**Comment by svchord** [comment]
这个应该是:has选择器的性能问题，下个版本改改

**Comment by svchord** [comment]
最新版已修改并上传，请等待集市打包上架或自行下载仓库到主题文件夹使用
