### ISSUE TITLE
评论功能点击无法打开之前的评论内容

### ISSUE THREAD

**Issue by xy0124** [svchord/Rem-Craft#86]
![image](https://user-images.githubusercontent.com/99000021/206185808-35382a97-1ae8-4ede-9dce-cfd3d63353a8.png)
如图，点击只能打开对话框，无法显示之前的内容。
实际打开应该是这样：
![image](https://user-images.githubusercontent.com/99000021/206186049-68f57860-8543-4559-888e-6ecdedf1b7bb.png)

**Comment by svchord** [comment]
其他主题的评论功能是否正常？这个功能并不是我开发的，所以我也不清楚怎么改…

**Comment by xy0124** [comment]
我下面的截图就是其他主题的。正常使用

**Comment by svchord** [comment]
最新版已修改并上传，请等待集市打包上架或自行下载仓库到主题文件夹使用
