### ISSUE TITLE
行级公式按 Ctrl + Enter 完成编辑后，光标丢失

### ISSUE THREAD

**Issue by zhanganchi352242** [svchord/Rem-Craft#88]
如下图
![RemCraft Bug反馈 行级公式](https://user-images.githubusercontent.com/50255967/206365422-18c400b5-1633-43a5-a983-28be487d1d3f.gif)
官方主题的行级公式在输入完毕后光标会出现在行级公式尾部，符合编辑习惯
![RemCraft Bug反馈 行级公式 官方主题](https://user-images.githubusercontent.com/50255967/206365540-462a926e-af9b-4058-a68b-b88d93d5a68e.gif)
我觉得这一点需要向官方主题看齐，现在每次编辑行级公式都需要重新点击鼠标，迫使正在打字的手离开键盘，蛮影响体验的

**Comment by zhanganchi352242** [comment]
好的好的

**Comment by zhanganchi352242** [comment]
经过测试，还需要在`plugin/index.js`中注释`import { bulletMain } from "./bullet/main.js";`才可以

**Comment by svchord** [comment]
萌佬已经解决这个问题了，下个版本修复，如果你觉得慢的话可以在`plugin/bullet/main.js`的第22行前加一行：

```javascript
  if (document.activeElement.classList.contains("protyle-wysiwyg")) {
```

然后再在第27行加一个`}`，重启即可

**Comment by zhanganchi352242** [comment]
好的好的

**Comment by svchord** [comment]
最新版已修改并上传，请等待集市打包上架或自行下载仓库到主题文件夹使用
