### ISSUE TITLE
Alt + B 反链面板底部提及的按钮被遮挡

### ISSUE THREAD

**Issue by zhanganchi352242** [svchord/Rem-Craft#90]
![image](https://user-images.githubusercontent.com/50255967/206857445-bbcf13a1-2462-4cd9-afde-7a373f6b29ff.png)
如图所示
Alt + 7 反链面板修了，但是今天发现 Alt + B 反链面板还挡着，虽然 Alt + B 反链面板知道的人不多

**Comment by svchord** [comment]
收到，下个版本修复

**Comment by svchord** [comment]
最新版已修改并上传，请等待集市打包上架或自行下载仓库到主题文件夹使用
