### ISSUE TITLE
页签被拖动至顶栏右上角各种按钮右侧时，按钮失效

### ISSUE THREAD

**Issue by zhanganchi352242** [svchord/Rem-Craft#91]
![image](https://user-images.githubusercontent.com/50255967/206857574-9c15fb4f-440c-47b8-ac9c-3f05409ade1f.png)
如图所示，当页签边界被拖到右边时，右上角控制只读切换、明亮暗黑、设置等等的按钮都点了没反应了

**Comment by svchord** [comment]
这个没办法，因为右边分屏的页签也是需要点击的，必定会冲突，所以只能是建议分屏情况下不要这么做

**Comment by svchord** [comment]
主题更新了，我先把这个issue关了，有问题再开一个
