### ISSUE TITLE
标题块上下空白在段落块和无序列表块中不一致

### ISSUE THREAD

**Issue by intelion2022** [svchord/Rem-Craft#92]
在段落块中，标题上方空白大一些，下方小一些，比较正常；但在无序列表中使用标题时，标题上下方的空白变成了上小下大，不太协调，如图。建议把完善无序列表中标题块上下空白大小，和段落块中效果一致。

![image](https://user-images.githubusercontent.com/116488969/206902061-fa08d276-51ad-4a21-856f-2f09b196e791.png)

**Comment by svchord** [comment]
收到，我看看怎么改

**Comment by svchord** [comment]
最新版已修改并上传，请等待集市打包上架或自行下载仓库到主题文件夹使用
