### ISSUE TITLE
关于无序列表的一点建议

### ISSUE THREAD

**Issue by intelion2022** [svchord/Rem-Craft#93]
建议无序列表前的符号按列表级别显示不同符号，个人建议是1级显示实心方块，2级显示实心圆点，3级显示空心圆点，4-6级、7-9级重复1-3级，这样的好处是比较容易区分在哪一级。效果如下图：
![image](https://user-images.githubusercontent.com/116488969/206902574-b59c6c19-ef36-4b2b-86da-f82230c9dfb2.png)

**Comment by svchord** [comment]
我个人不太喜欢这种，你可以用代码片段修改。另外，我觉得如果要区分级别其实可以用有序列表的

**Comment by svchord** [comment]
主题更新了，没什么问题我就关了

**Comment by intelion2022** [comment]
好的，谢谢
