### ISSUE TITLE
暗黑模式下, 日历栏的表头颜色是黑色

### ISSUE THREAD

**Issue by FantasyDream** [svchord/Rem-Craft#94]
![image](https://user-images.githubusercontent.com/24907641/206977791-6f9f2ed5-bbd8-439c-a981-19d33bac8f99.png)
如图, 日历栏的表头颜色是黑色, 导致看不清楚

**Comment by svchord** [comment]
emmm，因为这个日历不是我开发的，所以我也不太清楚怎么改……建议先别在暗黑模式下用这个了，等之后我自己搞一个看看

**Comment by svchord** [comment]
如上，已经有大佬出手修好了，请往集市更新主题
