### ISSUE TITLE
嵌入块SQL编辑窗口关闭按钮失效了

### ISSUE THREAD

**Issue by intelion2022** [svchord/Rem-Craft#95]
这里的关闭按钮失效了，点不了，要重启思源才行。如图：
![image](https://user-images.githubusercontent.com/116488969/207206580-e3055dd2-0a7a-49fe-be0b-de0d499be013.png)

**Comment by intelion2022** [comment]
在默认主题下是可以正常关闭的~

**Comment by svchord** [comment]
最新版已修改并上传，请等待集市打包上架或自行下载仓库到主题文件夹使用
