### ISSUE TITLE
添加下划线时希望能有预览

### ISSUE THREAD

**Issue by zhanganchi352242** [svchord/Rem-Craft#96]
如下图，为选中文本加粗及设斜体时，均能看出文字已发生了变化，但是添加下划线时表现出来毫无反应，好像失败了一样，这会增加输入时的摩擦力
![Ctrl + U](https://user-images.githubusercontent.com/50255967/208234311-b927ac15-e723-4c15-88d1-2b2e5b219cb1.gif)

**Comment by svchord** [comment]
最新版已修改并上传，请等待集市打包上架或自行下载仓库到主题文件夹使用
